#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""フェーズG: 大国追補イベント定義（G1〜G10）。"""

from __future__ import annotations

from gp_common import gp_nation_evt as n
from gp_common import gp_world_evt as w

GP_EVENTS: dict[str, list] = {
    # ── G1: 国家001 T1-20 初期統合の兆し ──
    "G1": [
        n(
            "G1", "NATION_001", 3, "MonsterAttack", "monster",
            "【最西端の統合王国】周辺で高脅威周期の到来をいち早く察知した。",
            "乱立する脆弱小国の一つとして、ターン3前後に脅威個体群の面的侵攻兆候を最西端でいち早く察知。個別防衛の限界を痛感し、統合防衛への転換を検討し始めた。",
            "「小国の盾では、面は守れない——隣国と線を引け。」",
            "高脅威周期の早期察知。",
            "「侵攻経路が、読める。」",
            "最西端の前線監視塔。",
            "「統合の、最初の兆し。」",
            "早期察知ボーナス。",
            month=4, day=11, hour=9,
            hist_suffix="EARLY_THREAT_SENSE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G01_001_STEP_01", level=5,
        ),
        n(
            "G1", "NATION_001", 6, "ShieldFortification", "domestic",
            "【最西端の統合王国】が地理的障壁を結線する空間防衛網の試案を立案した。",
            "山脈と大河を結線した空間防衛網の試案が立案された。地理的障壁を利用した面防衛の原型が、後の広域統合システムの技術的基盤となった。",
            "「山の稜線に柱を立て、河に流路障壁を張れ——面で拒め。」",
            "空間防衛網試案。",
            "「点の防衛から、線の防衛へ。」",
            "山脈と大河を結ぶ試験結晶柱。",
            "「千年覇権の、最初の設計図。」",
            "防衛網試案ボーナス。",
            month=7, day=22, hour=14,
            hist_suffix="SPATIAL_NET_DRAFT",
            zone="ZONE_WEST_SPATIAL_NET", mmo_flag="MMO_GP_G01_001_STEP_02", level=6,
        ),
        n(
            "G1", "NATION_001", 9, "LocalConflict", "conflict",
            "【最西端の統合王国】が周辺崩壊小国への庇護と結晶接続を開始した。",
            "崩壊が迫る周辺小国に対し、軍事庇護と引き換えに結晶炉接続を提案。冷徹な吸収の原型となる庇護宣言が最西端で始まった。",
            "「我らの網の下に入れ。結晶炉を接続すれば、生き延びられる。」",
            "庇護と結晶接続。",
            "「統合は、救済の形を取る。」",
            "避難民の列と接続される結晶塔。",
            "「広域統合の、前触れ。」",
            "庇護接続ボーナス。",
            month=10, day=5, hour=11,
            hist_suffix="SHELTER_CRYSTAL_LINK",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G01_001_STEP_03", level=7,
        ),
        n(
            "G1", "NATION_001", 13, "MagicPioneering", "domestic",
            "【最西端の統合王国】が近隣統治体の配給網を一本化する統合の兆しを示した。",
            "複数の近隣統治体の配給網を試験的に一本化。生存を前提とした領域統合としての「広域統合システム」の概念が、最西端で初めて実証段階に入った。",
            "「配給券が、一つの色に染まる——それが、統合だ。」",
            "配給網一本化。",
            "「小国群が、一つの経済圏へ。」",
            "統一色の配給網地図。",
            "「超大国への、最初の一歩。」",
            "統合兆しボーナス。",
            month=2, day=18, hour=16,
            hist_suffix="INTEGRATION_GLIMMER",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G01_001_STEP_04", level=8,
        ),
    ],
    # ── G2: 国家001 T21-60 ──
    "G2": [
        n(
            "G2", "NATION_001", 21, "LocalConflict", "conflict",
            "【最西端の統合王国】が百国時代の統合圧力を西方諸国に向け始めた。",
            "百国時代の生存闘争の中、最西端統合圏は周辺対抗勢力への統合圧力を本格化。軍事庇護と物量優位を武器に、西方の版図再編を主導し始めた。",
            "「生き残った国は、百——そのうち半分は、我らの傘下へ。」",
            "百国時代の統合圧力。",
            "「覇権争いが、加速する。」",
            "西方地図上の統合圏拡大。",
            "「二極化の、始まり。」",
            "統合圧力ボーナス。",
            related="NATION_015",
            month=3, day=8, hour=10,
            hist_suffix="HUNDRED_NATIONS_PRESSURE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G02_001_STEP_01", level=10,
        ),
        n(
            "G2", "NATION_001", 27, "ShieldFortification", "domestic",
            "【最西端の統合王国】が鉄血の軍政内政一体型構造へ移行した。",
            "余剰を排した軍政内政一体型構造への移行が完了。内政と軍事の境界が消え、後の絶対防衛圏維持と内周収縮の組織基盤が固まった。",
            "「配給所も兵舎も、同じ番号だ——鉄血のシステム。」",
            "鉄血軍政一体型。",
            "「文明より、拒否。」",
            "軍番号と配給券の都市。",
            "「常夜の底への、防具。」",
            "鉄血体制ボーナス。",
            month=6, day=19, hour=13,
            hist_suffix="IRON_MILITARY_STATE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G02_001_STEP_02", level=12,
        ),
        n(
            "G2", "NATION_001", 33, "LocalConflict", "conflict",
            "【最西端の統合王国】が西方二極冷戦構造の頂点へ押し上げた。",
            "南方の最大抵抗勢力との冷戦が固定化。全面衝突を避けつつ結晶の隠密奪い合いと生存空間の割当交渉が、西方の主要矛盾となった。",
            "「正面で打たない——結晶の輸送路を、静かに切れ。」",
            "二極冷戦の固定化。",
            "「巨大障壁と、分散の網。」",
            "二色に割れる西方地図。",
            "「第3章への、橋。」",
            "冷戦固定ボーナス。",
            related="NATION_015",
            month=11, day=2, hour=20,
            hist_suffix="BIPOLAR_COLD_WAR_PEAK",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G02_001_STEP_03", level=14,
        ),
        n(
            "G2", "NATION_001", 42, "ShieldFortification", "domestic",
            "【最西端の統合王国】が生存域選別に向けた内周収縮の準備を開始した。",
            "総国力最底期の前触れとして、外縁防衛拠点の段階的縮小と中核資源の集中計画が始動。後の内周死守と結晶備蓄の方針が最高統制部で承認された。",
            "「外縁は、捨てる——中核だけを、厚く。」",
            "内周収縮の準備。",
            "「生存域選別の、設計図。」",
            "縮小する防衛線と深部の備蓄庫。",
            "「常夜の底の、前夜。」",
            "収縮準備ボーナス。",
            month=5, day=14, hour=8,
            hist_suffix="INNER_WITHDRAWAL_PREP",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G02_001_STEP_04", level=16,
        ),
        n(
            "G2", "NATION_001", 53, "ShieldFortification", "domestic",
            "【最西端の統合王国】が中核結晶備蓄の完全死守体制を強化した。",
            "内周収縮後、中核深部の結晶備蓄庫を六百年分規模まで拡充。第4章の電撃遠征原動力となる資源温存が、暗黒期の最中に完成に近づいた。",
            "「倉庫は、まだ満ちる——外へ出る日のために。」",
            "中核備蓄強化。",
            "「捨てた土地の代わりに、守った結晶。」",
            "内周深部の巨大備蓄庫。",
            "「反撃の火種。」",
            "備蓄強化ボーナス。",
            month=9, day=27, hour=15,
            hist_suffix="CORE_RESERVE_EXPAND",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G02_001_STEP_05", level=18,
        ),
    ],
    # ── G3: 国家001 T61-100 ──
    "G3": [
        n(
            "G3", "NATION_001", 61, "MagicPioneering", "domestic",
            "【最西端の統合王国】が低脅威周期を感知し蓄積結晶の対外投入を決定した。",
            "脅威個体群の活動指数減退を感知。要塞内部に死守・蓄積していた膨大な固有エネルギー結晶の対外開拓投入を最高統制部が決定。大開拓時代の西方主導が始まった。",
            "「六百年分の結晶を、扉の外へ——夜明けだ。」",
            "蓄積結晶の解封決定。",
            "「雌伏の終わり。」",
            "開く要塞の門と結晶輸送列。",
            "「電撃遠征の、原動力。」",
            "結晶解封ボーナス。",
            month=2, day=1, hour=7,
            hist_suffix="RESERVE_UNSEAL_DECREE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G03_001_STEP_01", level=22,
        ),
        n(
            "G3", "NATION_001", 67, "LocalConflict", "conflict",
            "【最西端の統合王国】が統合王国樹立に向けた最終統合プロセスを開始した。",
            "周辺対抗軸の残存拠点を順次傘下に収める最終統合プロセスが開始。領域・西の単一巨大統治体への集約が不可逆の段階に入った。",
            "「百の旗が、一つの王冠へ——統合王国の誕生だ。」",
            "統合王国樹立プロセス。",
            "「覇権争いの、終幕。」",
            "西方大陸の統一旗。",
            "「一極支配の、完成。」",
            "王国樹立ボーナス。",
            month=8, day=16, hour=12,
            hist_suffix="KINGDOM_FOUNDING_PROCESS",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G03_001_STEP_02", level=24,
        ),
        n(
            "G3", "NATION_001", 73, "ShieldFortification", "domestic",
            "【最西端の統合王国】が領域・西の一極支配を不可逆と宣言した。",
            "領域・西の全統治体が統合王国を頂点とする単一秩序へ完全集約。人間同士の覇権争いが外因的脅威の減退とともに決着し、軍事的一極が確定した。",
            "「西方は、一つだ——異論を許さない。」",
            "一極支配の不可逆宣言。",
            "「統合王国の、完成。」",
            "単色の西方大陸地図。",
            "「大遠征への、政治基盤。」",
            "一極確定ボーナス。",
            month=4, day=23, hour=18,
            hist_suffix="WEST_UNIPOLAR_FINAL",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G03_001_STEP_03", level=25,
        ),
        n(
            "G3", "NATION_001", 79, "MonsterAttack", "monster",
            "【最西端の統合王国】が大遠征構想を最高統制部で正式承認した。",
            "統合王国の最高統制部が、領域・西全域から外因的脅威を完全駆逐する大遠征構想を正式承認。防衛から攻勢への完全転換が国家方針として固定された。",
            "「次は、追い払う——600年の防衛を、10年の攻勢で報いる。」",
            "大遠征構想承認。",
            "「能動的殲滅戦の、号令。」",
            "作戦室の大遠征地図。",
            "「第5章の、核心。」",
            "大遠征承認ボーナス。",
            month=10, day=7, hour=6,
            hist_suffix="EXPEDITION_PLAN_RATIFIED",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G03_001_STEP_04", level=27,
        ),
        n(
            "G3", "NATION_001", 89, "MonsterAttack", "monster",
            "【最西端の統合王国】が大遠征の中間戦果を世界に報告した。",
            "大遠征の中間段階で、最西端大陸の大半から脅威個体群の支配域が剥奪された。千年戦史における人類初の領域完全駆逐が目前であることが公的記録に報告された。",
            "「あと一押し——大陸は、人間のものになる。」",
            "大遠征中間戦果。",
            "「完全制圧空間の、直前。」",
            "清められる西方地図。",
            "「軍事覇権の、頂点。」",
            "中間戦果ボーナス。",
            month=12, day=15, hour=21,
            hist_suffix="EXPEDITION_MID_REPORT",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_GP_G03_001_STEP_05", level=29,
        ),
    ],
    # ── G4: 国家002 T1-20 障壁防衛網 ──
    "G4": [
        n(
            "G4", "NATION_002", 4, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が高密度エネルギー障壁網の基幹を確立した。",
            "東端部に位置する魔導生産大国は、初期より高密度エネルギー障壁網による防衛特化型経済を確立。静的拠点拒否戦術の基幹が完成した。",
            "「障壁は光り続けろ——東端の面を、止めろ。」",
            "高密度障壁網基幹。",
            "「防衛特化型経済の、起点。」",
            "光る東端障壁網。",
            "「千年防衛の、第一環。」",
            "障壁基幹ボーナス。",
            month=3, day=6, hour=11,
            hist_suffix="DENSE_BARRIER_CORE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G04_002_STEP_01", level=5,
        ),
        n(
            "G4", "NATION_002", 12, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が防衛特化型結晶生産体制を本格稼働させた。",
            "国内の結晶炉を防衛用出力に特化。余剰を排し、障壁維持と局所迎撃に全魔力を集中する経済構造が本格稼働した。",
            "「生産のすべてを、盾に回せ——攻めは、後だ。」",
            "防衛特化型生産。",
            "「経済が、防衛に従属する。」",
            "防衛向け結晶炉群。",
            "「東方大国の、経済原則。」",
            "特化生産ボーナス。",
            month=6, day=17, hour=14,
            hist_suffix="DEFENSE_ECONOMY_ONLINE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G04_002_STEP_02", level=7,
        ),
        n(
            "G4", "NATION_002", 14, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】の防衛戦区が周辺国の避難所として機能し始めた。",
            "東端防衛戦区が周辺崩壊国の避難所として機能。障壁内への避難民流入が始まり、後の技術伝播と人口集中の契機となった。",
            "「東の壁の内側なら、まだ灯がある——入れ。」",
            "避難所機能の開始。",
            "「防衛圏が、人を集める。」",
            "避難民の列と光る障壁。",
            "「東方の、引力。」",
            "避難所ボーナス。",
            month=9, day=3, hour=10,
            hist_suffix="SANCTUARY_ZONE_OPEN",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G04_002_STEP_03", level=8,
        ),
        n(
            "G4", "NATION_002", 17, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が東端防衛戦区の第一段完成を宣言した。",
            "国境沿いの大規模障壁網第一段が完成。面的侵攻を拒否する静的拠点戦術が実証され、第2章以降の焦土戦術・深層移行の防衛基盤が確立した。",
            "「第一段が、点灯した——東端は、まだ止まっている。」",
            "東端防衛戦区完成。",
            "「面拒否の、実証。」",
            "完成した障壁環。",
            "「焦土への、踏み台。」",
            "防衛戦区完成ボーナス。",
            month=11, day=28, hour=16,
            hist_suffix="EAST_DEFENSE_RING_DONE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G04_002_STEP_04", level=9,
        ),
    ],
    # ── G5: 国家002 T21-60 焦土・深層 ──
    "G5": [
        n(
            "G5", "NATION_002", 22, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が焦土エネルギー戦術の実戦投入を決定した。",
            "長引く猛攻に対し、国土の未来を犠牲にする「焦土エネルギー戦術」の実戦投入を決定。固有エネルギーの計画的放出による拒否戦略が、東方の国策となった。",
            "「土地を焼け——未来より、今日を取れ。」",
            "焦土戦術決定。",
            "「国土を、武器に変える。」",
            "焦土化が進む東方外周。",
            "「拒否戦略の、極致。」",
            "焦土決定ボーナス。",
            month=2, day=12, hour=8,
            hist_suffix="SCORCHED_DECREE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G05_002_STEP_01", level=11,
        ),
        n(
            "G5", "NATION_002", 28, "MonsterAttack", "monster",
            "【東方の魔導生産大国】が中央海平原への焦土拒否展開を開始した。",
            "中央海平原に向けた焦土エネルギー戦術の展開が開始。侵攻を鈍化させる代償として広域の環境破壊が進行し、後の荒野化の遠因となった。",
            "「平原に、灰を撒け——奴らの足を、止めろ。」",
            "中央海焦土展開。",
            "「環境の代償を、厭わない。」",
            "灰の中央海平原。",
            "「侵攻鈍化の、成功。」",
            "焦土展開ボーナス。",
            month=5, day=24, hour=19,
            hist_suffix="CENTRAL_SCORCHED_DEPLOY",
            zone="ZONE_CENTRAL_SEA_PLAIN", mmo_flag="MMO_GP_G05_002_STEP_02", level=13,
        ),
        n(
            "G5", "NATION_002", 32, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が国土犠牲を受容する拒否戦略を固定化した。",
            "焦土戦術による国土犠牲を国家方針として固定。地表生産の放棄と防衛密度の最大化が、深層魔導都市移行の思想的基盤となった。",
            "「土地は減った。盾は、厚くなった。」",
            "国土犠牲の固定化。",
            "「空間の放棄と、密度の交換。」",
            "縮小する東方版図。",
            "「深層への、思想的準備。」",
            "犠牲固定ボーナス。",
            month=8, day=7, hour=13,
            hist_suffix="LAND_SACRIFICE_DOCTRINE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G05_002_STEP_03", level=14,
        ),
        n(
            "G5", "NATION_002", 39, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が深層魔導都市移行の国家決断を下した。",
            "地表通常生産の完全停止を見据え、主要拠点の地下・遮蔽内部への移行を国家決断として下した。密閉型生存サイクルによる文明保護が国策化された。",
            "「地表を捨て、坑道の奥へ——文明は、地下に封じる。」",
            "深層移行決断。",
            "「失伝ではなく、保護。」",
            "地下入口の拡張工事。",
            "「常夜の底の、東方答え。」",
            "深層決断ボーナス。",
            month=11, day=19, hour=22,
            hist_suffix="DEEP_CITY_DECREE",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_GP_G05_002_STEP_04", level=16,
        ),
        n(
            "G5", "NATION_002", 44, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が密閉型生存サイクルの試験都市を完成させた。",
            "排熱と廃棄魔力を再利用する密閉型生存サイクルの試験都市が完成。外部ゼロで都市が回る実証が成功し、第3章後半の深層魔導都市の原型となった。",
            "「捨てる熱はない——全部、炉に戻せ。」",
            "密閉循環試験都市。",
            "「外部ゼロの、生存。」",
            "循環する地下結晶炉。",
            "「技術の、純化。」",
            "密閉試験ボーナス。",
            month=4, day=30, hour=6,
            hist_suffix="SEALED_CITY_PROTOTYPE",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_GP_G05_002_STEP_05", level=17,
        ),
    ],
    # ── G6: 国家002 T61-100 魔導大国 ──
    "G6": [
        n(
            "G6", "NATION_002", 61, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が脅威休眠を感知し地下資源の解封準備を開始した。",
            "脅威個体群の休眠兆候を感知。地下に蓄積された技術と人口の地表解放に向け、極限環境対応型固有エネルギー技術の解封準備が始動した。",
            "「眠る奴らを感知した——地下の炉を、外へ開け。」",
            "休眠感知・解封準備。",
            "「雌伏の終わり。」",
            "地下から伸びる試験結晶路。",
            "「魔導工学の、前夜。」",
            "解封準備ボーナス。",
            month=1, day=20, hour=9,
            hist_suffix="HIBERNATION_DETECTED",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_GP_G06_002_STEP_01", level=22,
        ),
        n(
            "G6", "NATION_002", 65, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が深層からの地表一斉解放を号令した。",
            "地下に蓄積されたすべての技術と人口を地表へ一気に解放する号令が下された。密閉時代で純化された結晶技術が、大開拓時代の主役となった。",
            "「坑道の奥から、全部出せ——地表は、取り返す。」",
            "地表一斉解放。",
            "「深層からの、凱歌。」",
            "地下都市から溢れる人口と技術。",
            "「再興の、始まり。」",
            "地表解放ボーナス。",
            month=5, day=11, hour=14,
            hist_suffix="SURFACE_LIBERATION_ORDER",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G06_002_STEP_02", level=23,
        ),
        n(
            "G6", "NATION_002", 72, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が魔導工学の広域展開を開始した。",
            "脅威残存素材を触媒とする魔導工学を領域・東全域に展開。資源生産効率が古代魔法時代を凌駕する水準へ急成長し、魔導生産大国の地位が確立された。",
            "「奴らの残骸を、全部、炉に——脅威を、糧に変える。」",
            "魔導工学広域展開。",
            "「コペルニクス的転換。」",
            "全域に広がる魔導工房。",
            "「生産大国の、確立。」",
            "魔導展開ボーナス。",
            month=8, day=26, hour=17,
            hist_suffix="ARCANE_ENGINEERING_SCALE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G06_002_STEP_03", level=25,
        ),
        n(
            "G6", "NATION_002", 76, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が共同再興圏の骨格設計を完了した。",
            "魔導技術と物流インフラを中心とした共同再興圏の骨格設計が完了。武力支配ではなく技術・経済提供による広域統合の蓝图が、第5章の双極秩序の東側支柱となった。",
            "「剣ではなく、炉と道路——一緒に、再興しよう。」",
            "共同再興圏骨格。",
            "「経済統合の、設計図。」",
            "東方から伸びる物流網。",
            "「双極の、東翼。」",
            "再興圏骨格ボーナス。",
            month=11, day=9, hour=20,
            hist_suffix="REVIVAL_BLOC_FRAME",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G06_002_STEP_04", level=26,
        ),
        n(
            "G6", "NATION_002", 95, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が経済・技術極として千年紀末の地位を確定した。",
            "共同再興圏による実質的経済統合の完成により、最西端統合圏の軍事的一極に対抗する世界最大の経済・技術極としての地位が確定。双極秩序の東側柱が千年史に楔を打った。",
            "「西の剣に、東の炉——二極が、世界を支える。」",
            "経済極地位確定。",
            "「22万の国力の、東側原動力。」",
            "双極世界地図。",
            "「千年の、均衡。」",
            "経済極確定ボーナス。",
            month=3, day=18, hour=12,
            hist_suffix="ECONOMIC_POLE_CONFIRMED",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_GP_G06_002_STEP_05", level=30,
        ),
    ],
    # ── G7: 国家015 T21-60 分散防衛 ──
    "G7": [
        n(
            "G7", "NATION_015", 22, "ShieldFortification", "domestic",
            "【西方大陸南部】が強固な軍政内政一体型システムを敷いた。",
            "領域・西の最大抵抗極として、強固な軍政内政一体型システムを敷いた。最西端統合圏の強硬な領域再編に対抗する組織基盤が、南方で確立された。",
            "「番号と配給券——だが、ここでは、独立の番号だ。」",
            "軍政一体型システム。",
            "「抵抗の、組織。」",
            "南方の軍番号都市。",
            "「001への、対抗軸。」",
            "軍政一体ボーナス。",
            related="NATION_001",
            month=2, day=9, hour=11,
            hist_suffix="MILITARY_INTEGRATION_015",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_GP_G07_015_STEP_01", level=10,
        ),
        n(
            "G7", "NATION_015", 29, "LocalConflict", "conflict",
            "【西方大陸南部】が最西端統合圏の領域再編に真っ向から反発した。",
            "最西端統合圏の強硬な領域再編に対し、南方勢力は真っ向から反発。武力衝突は回避しつつ、結晶流通と生存空間の割当を巡る冷戦的対立が始まった。",
            "「傘下に入るな——高地と地下に、自分の穴を掘れ。」",
            "領域再編への反発。",
            "「002への、最大抵抗。」",
            "対立する二色の西方地図。",
            "「冷戦の、始まり。」",
            "再編反発ボーナス。",
            related="NATION_001",
            month=6, day=21, hour=15,
            hist_suffix="REORG_RESISTANCE",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_GP_G07_015_STEP_02", level=12,
        ),
        n(
            "G7", "NATION_015", 34, "LocalConflict", "conflict",
            "【西方諸国間】で015を頂点とする西方二極冷戦が確立した。",
            "最西端統合圏と南方抵抗勢力の二極構造が西方で確立。全面戦争を避け、結晶の隠密奪い合いが主要矛盾となった。",
            "「巨大障壁と、百の小さな盾——西方は、二つに割れた。」",
            "西方二極冷戦確立。",
            "「相互統制の、時代。」",
            "二極の西方地図。",
            "「第3章の、前提。」",
            "二極確立ボーナス。",
            related="NATION_001",
            month=10, day=4, hour=19,
            hist_suffix="WEST_BIPOLAR_015",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_GP_G07_015_STEP_03", level=14,
        ),
        n(
            "G7", "NATION_015", 41, "ShieldFortification", "domestic",
            "【西方大陸南部】が分散型拠点網の構想を最高統制部で承認した。",
            "統合圏の内周収縮に先立ち、切り捨て外縁を想定した分散型拠点網（ゲリラ防衛）の構想が承認。後の外縁回収と高地・地下拠点群の設計図となった。",
            "「巨大障壁より、百の小さな盾——それが、我らの答えだ。」",
            "分散型拠点網構想。",
            "「ゲリラ防衛の、設計。」",
            "南方に張られる細い結晶網。",
            "「015の、生存戦略。」",
            "分散網構想ボーナス。",
            month=3, day=16, hour=8,
            hist_suffix="DISPERSED_NET_PLAN",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_GP_G07_015_STEP_04", level=16,
        ),
        n(
            "G7", "NATION_015", 51, "LocalConflict", "conflict",
            "【西方大陸南部】が結晶冷戦下でも分散拠点網を維持し続けた。",
            "最底期の結晶冷戦下、南方勢力は分散拠点網を維持。隠密奪い合いと生存空間交渉の中で、形式的独立と独自軍事伝統を死守し続けた。",
            "「正面で打たず、結晶の路を守れ——小さく、長く。」",
            "冷戦下の分散維持。",
            "「015の、執念。」",
            "細い結晶網が光り続ける南方。",
            "「統合への、抵抗の終わり。」",
            "冷戦維持ボーナス。",
            related="NATION_001",
            month=7, day=28, hour=13,
            hist_suffix="COLD_WAR_DISPERSAL_HOLD",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_GP_G07_015_STEP_05", level=18,
        ),
    ],
    # ── G8: 001×002 T80-100 双極外交 ──
    "G8": [
        n(
            "G8", "NATION_001", 82, "LocalConflict", "conflict",
            "【最西端の統合王国】が東方魔導大国へ双極外交使節を派遣した。",
            "領域・西の完全一極化後、東方魔導大国へ双極外交使節を派遣。軍事的一極と経済・技術的一極の共存条件を探る、千年紀末外交の始まりとなった。",
            "「西の剣は、東の炉と、衝突する必要はない——条件を話せ。」",
            "双極外交使節派遣。",
            "「新たなる大国間対立の、外交版。」",
            "西方から東方への使節列。",
            "「膠着の、始まり。」",
            "外交使節ボーナス。",
            related="NATION_002",
            month=4, day=12, hour=10,
            hist_suffix="DIPLOMATIC_ENVOY_WEST",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G08_DUAL_STEP_01", level=27,
        ),
        n(
            "G8", "NATION_002", 86, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が統合王国と魔導物流協定の草案を提示した。",
            "最西端統合圏への回答として、魔導技術と物流インフラを中心とした協定草案を提示。武力衝突を避け、経済的相互依存による膠着状態の設計が始まった。",
            "「剣を交えず、結晶の流通路を、共に使おう。」",
            "魔導物流協定草案。",
            "「経済で、覇権を。」",
            "東西を結ぶ物流網の草案。",
            "「双極の、契約。」",
            "物流協定ボーナス。",
            related="NATION_001",
            month=6, day=25, hour=14,
            hist_suffix="LOGISTICS_TREATY_DRAFT",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_GP_G08_DUAL_STEP_02", level=28,
        ),
        n(
            "G8", "NATION_001", 96, "LocalConflict", "conflict",
            "【最西端の統合王国】が双極膠着状態を国家方針として認定した。",
            "大遠征の完遂後、最西端統合圏は東方魔導大国との双極膠着状態を国家方針として認定。軍事的一極と経済・技術的一極の均衡が、千年紀末の国際秩序として固定された。",
            "「もう、共通の敵はいない——西の剣と、東の炉が、世界を挟む。」",
            "双極膠着の国家認定。",
            "「存亡の闘争から、覇権の均衡へ。」",
            "二極均衡の世界地図。",
            "「千年の、結末。」",
            "膠着認定ボーナス。",
            related="NATION_002",
            month=9, day=14, hour=18,
            hist_suffix="BIPOLAR_STALEMATE_RECOGNIZED",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G08_DUAL_STEP_03", level=30,
        ),
        w(
            "G8", 81, "MagicPioneering", "domestic",
            "【全世界】で二大巨頭による最終チェス盤が並べられた。",
            "最西端統合圏の軍事的一極と東方魔導大国の経済・技術的一極。外因的脅威が沈黙した世界で、次なる千年紀の最終局面に向けた大国間戦略的膠着の土台が形成された。",
            "「盤上の駒は、二つ——西の王と、東の炉。」",
            "最終チェス盤の形成。",
            "「脅威なき地表の、新均衡。」",
            "二極を示す世界地図。",
            "「第5章の、外交戦。」",
            "チェス盤形成ボーナス。",
            month=1, day=8, hour=12,
            hist_suffix="FINAL_CHESSBOARD",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G08_DUAL_STEP_04", level=27,
        ),
    ],
    # ── G9: 世界 T95-100 最終データ ──
    "G9": [
        w(
            "G9", 96, "MagicPioneering", "domestic",
            "【全世界】で総国力20万超の加速的上昇が観測された。",
            "ターン96時点で人類総国力の加速的上昇が観測。初期19,340の10倍超へ向かう極大値の前段階として、魔導工学と広域物流網の成果が数値に反映され始めた。",
            "「曲線が、垂直に近づく——千年の、結晶。」",
            "総国力20万超加速。",
            "「10倍の、前段階。」",
            "急上昇する国力曲線。",
            "「最終データの、接近。」",
            "国力加速ボーナス。",
            month=3, day=22, hour=10,
            hist_suffix="POWER_SURGE_200K",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G09_WORLD_STEP_01", level=30,
        ),
        w(
            "G9", 97, "MagicPioneering", "domestic",
            "【全世界】で平均脅威度0.5の安定水準が確定的となった。",
            "脅威個体群の活性が完全抑制され、平均脅威度0.5という観測史上最低の安定水準が確定的となった。低脅威周期の最終段階が、公的記録に刻まれた。",
            "「0.5——脅威は、ほぼ、眠っている。」",
            "脅威0.5確定。",
            "「600年ぶりの、静けさ。」",
            "沈黙する脅威度メーター。",
            "「駆逐の、成果。」",
            "脅威安定ボーナス。",
            month=7, day=6, hour=15,
            hist_suffix="THREAT_05_CONFIRMED",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_GP_G09_WORLD_STEP_02", level=31,
        ),
        w(
            "G9", 99, "MagicPioneering", "domestic",
            "【全世界】で最終確定値226,151・68国が記録され停止が近づいた。",
            "ターン99時点で生存国数68、人類総国力226,151.04、平均脅威度0.5という最終確定値が記録され、シミュレーション停止が目前に迫った。",
            "「226,151——68の太陽——0.5の静寂。」",
            "最終確定値記録。",
            "「千年の、数字。」",
            "最終データパネル。",
            "「停止直前。」",
            "最終値ボーナス。",
            month=11, day=29, hour=23,
            hist_suffix="FINAL_METRICS_LOCKED",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G09_WORLD_STEP_03", level=32,
        ),
    ],
    # ── G10: 世界 欠番・滅亡統計 ──
    "G10": [
        w(
            "G10", 14, "MagicPioneering", "domestic",
            "【全世界】で早期淘汰期における生存国家数の急減が記録された。",
            "第1章前半において生存国家数が131から急減。高脅威周期の面的侵攻により、北方・外周の統治体が次々と組織的統治能力を喪失したことが、公的統計に初めて集計された。",
            "「灯が、次々と消える——131は、もう、数字の記憶だ。」",
            "早期淘汰統計。",
            "「第1章の、大量滅亡。」",
            "消えていく地図上の灯火。",
            "「淘汰の、記録。」",
            "早期淘汰ボーナス。",
            month=5, day=10, hour=11,
            hist_suffix="EARLY_COLLAPSE_STATS",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_GP_G10_WORLD_STEP_01", level=8,
        ),
        w(
            "G10", 47, "MagicPioneering", "domestic",
            "【全世界】で第3章暗黒期の大量滅亡が観測史上最悪に達した。",
            "ターン47前後、第3章暗黒期の大量滅亡がピーク。総国力12,017付近の最底期と88カ国までの減少が、千年史の最低点として統計に刻まれた。",
            "「88——最底の、数字。」",
            "暗黒期滅亡ピーク。",
            "「12017——国力の、底。」",
            "最底期の国力曲線。",
            "「常夜の底の、統計。」",
            "暗黒期統計ボーナス。",
            month=8, day=19, hour=16,
            hist_suffix="DARK_AGE_COLLAPSE_PEAK",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_GP_G10_WORLD_STEP_02", level=18,
        ),
        w(
            "G10", 72, "MagicPioneering", "domestic",
            "【全世界】で新生国の誕生と短命滅亡の周期が記録整理された。",
            "第4章前半において、新生国の誕生と短命滅亡が短期間に集中。発展的統合前の过渡的統治体の統計が整理され、後の70カ国集約への過渡期として記録された。",
            "「生まれて、すぐ消える国——過渡期の、統計。」",
            "新生短命滅亡周期。",
            "「発展的統合の、前段。」",
            "短命な灯火の地図。",
            "「再編の、記録。」",
            "新生周期ボーナス。",
            month=2, day=27, hour=13,
            hist_suffix="BIRTH_COLLAPSE_CYCLE",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G10_WORLD_STEP_03", level=24,
        ),
        w(
            "G10", 88, "MagicPioneering", "domestic",
            "【全世界】で131から68への千年淘汰統計が最終整理された。",
            "千年の終わりに、131カ国から68カ国への淘汰・統合・再編の全統計が最終整理。欠番を含む滅亡国家の記録が、教科書的千年史の統計付録として確定した。",
            "「131から68——63の灯は、消えた。だが、10倍の国力が、残った。」",
            "千年淘汰統計整理。",
            "「欠番も、記録の一部。」",
            "131→68の統計年表。",
            "「千年史の、付録。」",
            "淘汰統計ボーナス。",
            month=10, day=3, hour=9,
            hist_suffix="MILLENNIUM_COLLAPSE_LEDGER",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_GP_G10_WORLD_STEP_04", level=29,
        ),
    ],
}
