#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""フェーズS: macroTurn ごとの世界規模イベント定義。"""

from __future__ import annotations

from spine_common import nation_ref_evt, world_evt

# macroTurn -> list[dict]
SPINE_WORLD_BY_TURN: dict[int, list[dict]] = {
    1: [
        world_evt(
            1, "MonsterAttack", "monster",
            "【全世界】で脅威個体群の平均脅威度が1.232に達し、初期高脅威周期が始まった。",
            "公的記録の初期段階において独立統治体は131、人類総国力は19,340付近であった。この時期を境に世界全体の平均脅威度が1.232という極めて高い水準に達し、約200年間の最初の高脅威周期が幕を開けた。",
            "「空が歪む。前線すべてに同時に警報が鳴った——これは散発ではない。」",
            "面的侵攻の開始。全世界の防衛線が同時圧迫。",
            "「広範な前線が一斉に押し上げられた。相互融通はもはや不可能だ。」",
            "地平線に複数方向からの脅威の影。",
            "「初期大崩壊時代の最初の十年が始まった。」",
            "高脅威周期開始ボーナス。",
            month=1, day=3, hour=6,
            hist_suffix="HIGH_THREAT_CYCLE_ONSET",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_01", level=3,
        ),
        world_evt(
            1, "MagicPioneering", "domestic",
            "【全世界】で都市間物流網と固有エネルギー伝達経路が寸断された。",
            "高脅威周期開始直後、既存社会インフラの破砕に伴う文明後退が始まった。都市間物流網と固有エネルギー伝達経路が初期段階で寸断され、孤立した地方集落の維持が困難となった。",
            "「街道が途切れた。結晶の送電路も沈黙した。各地が島になった。」",
            "物流断絶。広域経済の停止。",
            "「自給自足的な生存闘争へ移行せざるを得ない。」",
            "途切れた街道と暗転した送電結晶。",
            "「生存領域の縮小が全世界で同時に進んだ。」",
            "物流断絶デバフ。",
            month=7, day=18, hour=14,
            hist_suffix="LOGISTICS_SEVERANCE",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_CYCLE_STEP_02", level=4,
        ),
    ],
    2: [
        world_evt(
            2, "MonsterAttack", "monster",
            "【全世界】で生存を脅かされる統治体が続出し、人類総国力が減退し始めた。",
            "ターン2（10年目）には人類総国力は19,255付近へ減退し、生存を脅かされる国家が続出した。面的侵攻は散発的ではなく、防衛リソースの相互融通は事実上不可能な状態に陥った。",
            "「前線から次々と統治の色が消えていく。援軍は来ない。」",
            "初の大量淘汰の前兆。総国力の減退開始。",
            "「二つの統治体が地図から消えた——最初の欠番が始まった。」",
            "地図上で暗転する小さな領域。",
            "「初期大崩壊の第二十年が、淘汰の歯車を回し始めた。」",
            "淘汰開始ボーナス。",
            month=2, day=14, hour=8,
            hist_suffix="FIRST_ATTRITION_WAVE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_03", level=4,
        ),
    ],
    3: [
        world_evt(
            3, "MonsterAttack", "monster",
            "【全世界】で第1波大量淘汰が進行し、生存国家数が急減した。",
            "ターン3（20年目）からターン4（30年目）にかけて総国力は19,145付近まで連続減少し、備蓄物資の枯渇と生産基盤の損壊が恒常化した。広域前線の同時崩壊により多数の脆弱統治体が組織的統治能力を喪失した。",
            "「一日に複数の前線が割れる。欠番が地図を埋め尽くす。」",
            "大量淘汰の第1波。生存国家数の急減。",
            "「防衛密度の低い外周から、次々と消えていく。」",
            "地図に広がる無主地帯。",
            "「第1章最初期の大量淘汰が本格化した。」",
            "第1波淘汰ボーナス。",
            month=5, day=9, hour=17,
            hist_suffix="MASS_EXTINCTION_WAVE_1",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_04", level=5,
        ),
    ],
    4: [
        world_evt(
            4, "MagicPioneering", "domestic",
            "【全世界】で備蓄枯渇と生産基盤損壊が恒常化した。",
            "ターン4（30年目）時点で総国力は19,047付近まで低下。各国における備蓄物資の枯渇と生産基盤の損壊が恒常化し、広域経済活動は完全に停止した。",
            "「倉庫は空だ。工房は焼けた。生産は防衛だけに流れる。」",
            "備蓄枯渇の恒常化。",
            "「自給自足的生存闘争が全世界の標準になった。」",
            "空の倉庫と止まった街道。",
            "「文明後退が不可逆の日常になった。」",
            "備蓄枯渇デバフ。",
            month=9, day=21, hour=11,
            hist_suffix="SUPPLY_DEPLETION_NORM",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_CYCLE_STEP_05", level=5,
        ),
    ],
    5: [
        world_evt(
            5, "MonsterAttack", "monster",
            "【全世界】で周辺小規模統治体の連鎖瓦解が加速した。",
            "ターン5（40年目）前後、世界各地で周辺の小規模統治体が次々と瓦解。防衛リソースの大半を障壁維持に割く国家では国内経済循環が破綻し、脆弱な外周から淘汰が加速した。",
            "「小さな統治体の色が地図から消える。音もなく、次々と。」",
            "小規模国連鎖瓦解。",
            "「生存密度の低い領域から、淘汰の波が内側へ。」",
            "消えゆく外周の灯火。",
            "「第1章中盤の連鎖瓦解が始まった。」",
            "連鎖瓦解ボーナス。",
            month=4, day=6, hour=13,
            hist_suffix="PERIPHERY_CHAIN_COLLAPSE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_06", level=6,
        ),
        nation_ref_evt(
            "NATION_002", 5, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が高密度エネルギー障壁網で周囲の面的侵攻を阻み続けた。",
            "領域・東の東端部は、大規模障壁網を国境沿いに展開し静的拠点による拒否戦術で面的侵攻を当初は完全に阻んだ。周辺国にとって一種の避難所として機能したが、維持には国内生産リソースの大部分を障壁へ割かねばならなかった。",
            "「障壁は光り続けろ。周囲が崩れても、ここだけは止める。」",
            "障壁網維持。防衛特化型経済への転換開始。",
            "「避難民の流入が始まった。配給と治安が限界に近づく。」",
            "東端に連なる結晶障壁の光。内側に避難民の集落。",
            "「孤立無援の防衛線死守が始まった。」",
            "障壁網ボーナス。",
            month=8, day=19, hour=10,
            hist_suffix="EAST_BARRIER_RING",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_BARRIER_STEP_01", level=7,
        ),
    ],
    6: [
        world_evt(
            6, "MonsterAttack", "monster",
            "【全世界】で第2波大量淘汰が進行し、生存国家数が八十台前半まで減少した。",
            "ターン6（60年目）前後、第2波の面的攻撃により生存国家数は八十余まで急減。脆弱な統治体の淘汰が加速し、残存国家は主要防衛都市周辺への生存領域縮小を余儀なくされた。",
            "「地図の半分が無主地になった。生き残るのは要塞だけだ。」",
            "第2波大量淘汰。",
            "「外周はすべて危険地帯に変わった。」",
            "広がる無主地帯の暗色。",
            "「淘汰の歯車がさらに加速した。」",
            "第2波淘汰ボーナス。",
            month=6, day=28, hour=15,
            hist_suffix="MASS_EXTINCTION_WAVE_2",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_07", level=7,
        ),
    ],
    7: [
        world_evt(
            7, "MagicPioneering", "domestic",
            "【全世界】で生存領域の内周縮小が同時多発的に進んだ。",
            "ターン7（70年目）前後、各国は生存領域を主要防衛都市周辺へ縮小せざるを得ず、それ以外の全域が脅威個体群の遊弋する危険地帯へ変貌した。人類社会は自給自足的な生存闘争へ完全移行した。",
            "「外周は捨てるか、守れないか——どちらにせよ地図は縮む。」",
            "内周縮小の同時多発。",
            "「過密都市型防衛への移行が各地で始まった。」",
            "縮小された光の輪と外側の暗闇。",
            "「領土の広さが弱点であることが証明され始めた。」",
            "内周縮小ボーナス。",
            month=3, day=11, hour=9,
            hist_suffix="INNER_CONTRACTION_WAVE",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_08", level=7,
        ),
        nation_ref_evt(
            "NATION_002", 7, "MonsterAttack", "monster",
            "【東方の魔導生産大国】で避難民流入が配給制度と治安維持の限界に達した。",
            "周囲の崩壊国家から流入する大量避難民の受け入れにより、国内配給制度および治安維持機能が限界に達した。障壁維持と難民救済の両立が組織的に破綻寸前となった。",
            "「糧は尽きる。障壁の結晶も尽きる。だが扉は開けられない。」",
            "配給限界。治安悪化。",
            "「避難民の帳簿が防衛の帳簿を上回った。」",
            "障壁の内側に溢れる避難民の列。",
            "「孤立防衛線の社会的限界が露わになった。」",
            "難民危機デバフ。",
            month=10, day=2, hour=18,
            hist_suffix="EAST_REFUGEE_CRISIS",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_BARRIER_STEP_02", level=8,
        ),
    ],
    8: [
        world_evt(
            8, "MonsterAttack", "monster",
            "【全世界】で淘汰の勢いが緩みつつも生存国家数は七十台後半まで減少した。",
            "ターン8（80年目）時点で生存国家数は七十余まで減少。淘汰の第一波は落ち着きつつも、脆弱統治体の消滅は続き、残存国家の防衛密度は極限まで高まった。",
            "「消える国はまだある。だが、要塞化した国は持ちこたえ始めた。」",
            "淘汰の鈍化と要塞化の始まり。",
            "「生き残った統治体は、皆が要塞の形をしている。」",
            "各地に立ち上がる内周の城壁。",
            "「構造淘汰の第1段階が完了に近づいた。」",
            "要塞化ボーナス。",
            month=7, day=16, hour=12,
            hist_suffix="FORTRESS_SURVIVORS",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_09", level=8,
        ),
    ],
    9: [
        world_evt(
            9, "MagicPioneering", "domestic",
            "【全世界】で防衛特化型内政への構造転換が残存国家に普及した。",
            "ターン9（90年目）前後、残存国家は資源配給制・軍政一体化・固有エネルギー技術の防衛特化型改造を完了しつつあった。莫大な領土と人口を喪失した代わりに、残存領域の防衛密度を極限まで高める構造転換が進んだ。",
            "「農も商も、すべてが防衛のためだ。国家は要塞になる。」",
            "防衛特化型内政の普及。",
            "「文明の多様性を切り捨ててでも、組織的絶滅だけは回避する。」",
            "要塞化した都市の結晶光。",
            "「生存モデルの多様化が始まった。」",
            "防衛特化ボーナス。",
            month=11, day=8, hour=14,
            hist_suffix="DEFENSE_SPECIALIZATION",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_10", level=8,
        ),
    ],
    10: [
        world_evt(
            10, "MonsterAttack", "monster",
            "【全世界】で第1世紀の終わりに生存国家数が七十前後まで減少した。",
            "ターン10（100年目）を迎えた時点で生存国家数は七十前後まで急減した。初期131統治体のうち過半数が淘汰され、人類はかろうじて組織的絶滅を回避する構造を構築し始めた。",
            "「百年の終わりに、地図の色は半分以下になった。」",
            "第1世紀終端。生存国家七十前後。",
            "「淘汰は終わらない。だが、要塞は学習した。」",
            "百年紀念の地図に残る七十の灯火。",
            "「第1章前半の終わり——生存闘争は続く。」",
            "第1世紀完走ボーナス。",
            month=12, day=31, hour=23,
            hist_suffix="CENTURY_ONE_CLOSE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_11", level=9,
        ),
        nation_ref_evt(
            "NATION_002", 10, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が段階的縮小戦術で防衛線を内周都市部へ後退させた。",
            "長期間の限界的障壁維持により国境付近のエネルギー結晶基盤が疲弊し、局所的突破を許す事例が増加。指導層は防衛線をより内周の都市部へ後退させる段階的縮小戦術を余儀なくされた。",
            "「外周の耕作地は捨てろ。都市の核だけを守れ——それが命取りになるか、命綱になるか。」",
            "段階的縮小の断行。",
            "「多くの周辺耕作地が放棄され、食糧危機が領域東全域を襲った。」",
            "内側に後退する障壁線。外周の放棄された畑。",
            "「組織的生命線を次世代へ繋ぐ唯一の手段を選んだ。」",
            "段階的縮小ボーナス。",
            month=5, day=24, hour=7,
            hist_suffix="EAST_INNER_RETREAT",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_BARRIER_STEP_03", level=9,
        ),
        nation_ref_evt(
            "NATION_045", 10, "ShieldFortification", "domestic",
            "【中央海激戦区内周都市帯】が外周八割放棄と技術集約で高脅威周期を凌いだ。",
            "広域領土国家は高脅威周期の猛攻に直面し即座に外周領土の八割放棄を選択。全人口と固有エネルギー技術者を内周都市へ移住させ、防衛密度を爆発的に高めて脅威度1.232の猛攻を弾き返した。",
            "「外周は捨てろ。人も技術も内周へ——密度が命だ。」",
            "内周集約防衛の成功。",
            "「領土の広さは弱点——過密都市型技術集約が生存を証明した。」",
            "内周に過密な光の城壁。外周の静寂。",
            "「失われぬ古代エネルギー技術のシェルターとして機能し始めた。」",
            "技術集約生存ボーナス。",
            month=9, day=15, hour=11,
            hist_suffix="CENTRAL_INNER_CONTRACT",
            zone="ZONE_CENTRAL_INNER_CORE", mmo_flag="MMO_ZONE_CENTRAL_INNER_STEP_01", level=8,
        ),
    ],
    11: [
        world_evt(
            11, "MonsterAttack", "monster",
            "【最西端統合圏周辺】で微小統治体の無政府状態が始まった。",
            "ターン11（110年目）からターン15（150年目）の期間、領域・西では多数の微小統治体が個別方針で対応するも脆弱な防衛力の前に次々と瓦解。最も凄惨な無政府状態の世紀として記録された。",
            "「西方の地図が灰色に染まる。小さな統治の色が、音もなく消えていく。」",
            "西方無政府状態の開始。",
            "「脆弱な小国は、面的侵攻の前に抵抗できない。」",
            "西方に広がる無主地帯。",
            "「西方無政府の世紀が始まった。」",
            "西方動乱ボーナス。",
            month=3, day=8, hour=10,
            hist_suffix="WEST_ANARCHY_ONSET",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_01", level=9,
        ),
        nation_ref_evt(
            "NATION_001", 11, "ShieldFortification", "domestic",
            "【最西端の統合王国】が地理的障壁を用いた空間防衛網の構築に着手した。",
            "数ある脆弱な国家の一つだった勢力は、脅威個体群の侵攻経路を分析し、山脈および大河川を利用した効率的な空間防衛網の構築に着手。後の広域統合の原型となった。",
            "「山と川を盾にせよ。侵攻経路は地図に書いてある——そこに壁を張れ。」",
            "空間防衛網の原型。",
            "「分散した小国とは異なる、面的防衛の設計図が描かれた。」",
            "山脈と河川に沿う防衛線の光。",
            "「初期統合への最初の一歩が踏み出された。」",
            "空間防衛網ボーナス。",
            month=10, day=17, hour=8,
            hist_suffix="SPATIAL_DEFENSE_NET",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_00", level=9,
        ),
    ],
    12: [
        world_evt(
            12, "MonsterAttack", "monster",
            "【北方前線】で早期淘汰の第一波が本格化した。",
            "ターン12（120年目）前後、北方および西方の脆弱統治体における早期淘汰が本格化。静的防衛に依存した外周国家から組織的統治能力の喪失が相次いだ。",
            "「北方の氷壁が砕ける音が、地図の縁から聞こえる。」",
            "北方早期淘汰の第一波。",
            "「外周の防衛モデルが、次々と限界を露わにする。」",
            "北方に広がる砕けた防壁の残光。",
            "「早期欠番国の時代が始まった。」",
            "北方淘汰ボーナス。",
            month=6, day=22, hour=5,
            hist_suffix="NORTH_EARLY_EXTINCTION",
            zone="ZONE_NORTH_FRONTIER", mmo_flag="MMO_WORLD_NORTH_STEP_01", level=9,
        ),
    ],
    13: [
        world_evt(
            13, "MonsterAttack", "monster",
            "【全世界】で北方・西方の同時多発崩壊が第1章後半の淘汰波となった。",
            "ターン13（130年目）前後、北方沿岸と西方外周で同時多発的な組織崩壊が進行。脆弱な防衛モデルを持つ国家が短期間に組織的統治能力を喪失した。",
            "「一日に複数の統治の色が消える——地図が書き換わる速度が上がった。」",
            "同時多発崩壊。",
            "「防衛リソースの融通は、もはやどこにも届かない。」",
            "地図上に広がる欠番の帯。",
            "「第1章後半の淘汰波が本格化した。」",
            "同時崩壊ボーナス。",
            month=2, day=11, hour=16,
            hist_suffix="SIMULTANEOUS_COLLAPSE_WAVE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_12", level=10,
        ),
    ],
    14: [
        world_evt(
            14, "MonsterAttack", "monster",
            "【北方極寒帯】で静的氷壁依存国家の供給限界が一斉に露呈した。",
            "ターン14（140年目）前後、寒冷期に異常活性化した脅威個体群の集中突入により、天然防魔結晶に依存した静的氷壁モデルの供給限界が一斉に露呈。北方外周から組織的統治能力の喪失が連鎖した。",
            "「結晶庫が空のまま、氷壁だけが光っている——次の波で全て砕ける。」",
            "静的氷壁モデルの限界露呈。",
            "「理論化前の固定出力防衛が、一斉に破綻した。」",
            "砕け散る氷壁の青白い残光。",
            "「北方淘汰の最悪の年として記録された。」",
            "氷壁連鎖破綻ボーナス。",
            month=1, day=28, hour=4,
            hist_suffix="ICE_WALL_CHAIN_FAILURE",
            zone="ZONE_NORTH_FROZEN_PLAIN", mmo_flag="MMO_WORLD_NORTH_STEP_02", level=10,
        ),
    ],
    15: [
        world_evt(
            15, "LocalConflict", "conflict",
            "【最西端統合圏周辺】で生存を前提とした領域統合が冷徹に進行した。",
            "ターン15（150年目）前後、西方無政府状態の最中、軍事的庇護と引き換えに近隣のエネルギー生産基盤を併合する生存前提の領域統合が断行された。被統合国にとっては主権喪失だが、生存確率を高める現実的選択として受け入れられた。",
            "「旗を降ろせば生きられる。結晶炉を預ければ、壁の内側に入れる。」",
            "生存前提の領域統合。",
            "「主権か生存か——西方では答えが決まり始めた。」",
            "統合される結晶塔の配線色の変化。",
            "「西方無政府の世紀が、統合の世紀へ転じ始めた。」",
            "領域統合ボーナス。",
            month=8, day=5, hour=13,
            hist_suffix="SURVIVAL_INTEGRATION",
            related="NATION_001",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_01", level=10,
        ),
    ],
    16: [
        world_evt(
            16, "MonsterAttack", "monster",
            "【北方凍土帯】で遊牧採掘共同体の氷壁防衛が冬季面攻撃に崩れた。",
            "ターン16（160年目）前後、寒冷期の異常活性化による執拗な面攻撃で、結晶供給限界に達した静的氷壁が一斉破砕。遊牧採掘型の防衛共同体から組織的統治能力の喪失が相次いだ。",
            "「極寒の前線で隊列が消えた。氷壁の破片だけが凍土に残る。」",
            "北方共同体の氷壁破砕。",
            "「固定出力の防衛は、環境変動に弱い——教訓が血で刻まれた。」",
            "凍土に埋もれる砕氷。",
            "「北方早期淘汰の第二波が完了した。」",
            "氷壁破砕ボーナス。",
            month=7, day=19, hour=3,
            hist_suffix="NORTH_COMMUNITY_ICE_BREAK",
            zone="ZONE_NORTH_FROZEN_PLAIN", mmo_flag="MMO_WORLD_NORTH_STEP_03", level=10,
        ),
        nation_ref_evt(
            "NATION_001", 16, "LocalConflict", "conflict",
            "【最西端の統合王国】が周辺小国群の吸収拡大を加速させた。",
            "ターン16（160年目）から統合中核勢力の支配領域は周辺の小国群を飲み込みながら拡大。個別の分散防衛力から集約された広域防衛組織へ進化し始めた。",
            "「小さな旗を降ろした国から、結晶炉と防衛線を一つに繋げろ。」",
            "小国群吸収の加速。",
            "「統合の歯車が、西方で強力に回り始めた。」",
            "拡大する統合圏の配線網。",
            "「人間同士の集約化が、共通の脅威への応答として始動した。」",
            "吸収拡大ボーナス。",
            month=11, day=26, hour=15,
            hist_suffix="ABSORPTION_EXPANSION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_02", level=11,
        ),
    ],
    17: [
        world_evt(
            17, "MagicPioneering", "domestic",
            "【全世界】で統合圏内の総国力回復が始まった。",
            "ターン17（170年目）前後、西方の統合と各地の防衛特化が進み、人類総国力の回復傾向が始まった。脆弱統治体の淘汰と強力な複合国家への集約という構造転換が数値に反映され始めた。",
            "「滅びた国の結晶炉が、生き残った国の炉に接続され始める。」",
            "総国力回復の始まり。",
            "「敗北ではない——構造の再編だ。」",
            "統合された配給網の脈動。",
            "「集約化が国力の底上げを始めた。」",
            "国力回復ボーナス。",
            month=4, day=13, hour=10,
            hist_suffix="HUMAN_POWER_RECOVERY",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_CYCLE_STEP_13", level=10,
        ),
    ],
    18: [
        nation_ref_evt(
            "NATION_001", 18, "MagicPioneering", "domestic",
            "【最西端の統合王国】が広域統合システムを本格稼働させた。",
            "生存を前提とした領域統合として、軍事庇護と引き換えに近隣のエネルギー生産基盤を併合する広域統合システムが本格化。冷徹な吸収が統合圏の拡大を加速させた。",
            "「庇護を求める小国が次々と使者を送る。結晶炉を我らの網に接続せよ。」",
            "広域統合システム本格稼働。",
            "「第二環が完成した。旧国境の塔が一つの配給網に収束する。」",
            "統合圏に広がる結晶配線の光。",
            "「分散防衛から集約防衛組織への進化が始まった。」",
            "統合システムボーナス。",
            month=9, day=22, hour=14,
            hist_suffix="INTEGRATION_SYSTEM",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_01", level=10,
        ),
    ],
    19: [
        world_evt(
            19, "ShieldFortification", "domestic",
            "【全世界】で防衛密度の極限化が残存国家に普及し終えた。",
            "ターン19（190年目）前後、残存国家は資源配給制・軍政一体化・固有エネルギー技術の防衛特化型改造を完了しつつあった。残存領域の防衛密度は極限まで高まった。",
            "「生き残った領土は小さい。だが、壁は厚い。」",
            "防衛密度の極限化完了。",
            "「組織的絶滅回避の構造が、ほぼ形になった。」",
            "各地の内周要塞の結晶光。",
            "「第2世紀末が近づく。」",
            "防衛極限化ボーナス。",
            month=5, day=30, hour=11,
            hist_suffix="DEFENSE_DENSITY_PEAK",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_14", level=11,
        ),
    ],
    20: [
        world_evt(
            20, "MagicPioneering", "domestic",
            "【全世界】で第1章が終わり、生存国家は百十前後へ構造転換した。",
            "ターン20（200年目）時点で生存国家数は当初131から百十前後へ急減した。総国力は約16,000付近まで低下したが、これは脆弱統治体の淘汰と複合国家への集約という構造転換を意味する。第2章の土台が築かれた。",
            "「二百年の終わりに、地図は百十の灯火だけになった。だが、それぞれの光は強い。」",
            "第1章完結。構造転換の確立。",
            "「滅びは終わらない。だが、生き残り方は学習した。」",
            "百年紀の終わりの地図。百十の要塞の光。",
            "「第2章——瓦解と同盟の時代へ。」",
            "第1章完走ボーナス。",
            month=12, day=20, hour=18,
            hist_suffix="CHAPTER_ONE_COMPLETE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_15", level=12,
        ),
        nation_ref_evt(
            "NATION_001", 20, "ShieldFortification", "domestic",
            "【最西端の統合王国】が集約広域防衛組織へ進化し第2章の覇権基盤を築いた。",
            "ターン20（200年目）までに統合中核勢力は周辺小国群を飲み込み、個別分散防衛力から集約された広域防衛組織へ進化。次なる200年間の覇権闘争の土台となった。",
            "「千年紀の西方図で、統合圏の色はもう一つに近づいている。」",
            "広域防衛組織の確立。",
            "「生存を担保とした統合政策が、歴史のパラダイムを動かした。」",
            "西方に広がる統合防衛網の光。",
            "「第2章の覇権闘争の土台が築かれた。」",
            "覇権基盤ボーナス。",
            month=10, day=8, hour=9,
            hist_suffix="WEST_HEGEMONY_BASE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_03", level=12,
        ),
        nation_ref_evt(
            "NATION_002", 20, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が防衛特化型経済の生存モデルを確立した。",
            "第1章を通じて東方大国は全リソースを高密度エネルギー障壁の維持へ強制一本化し、国家そのものを巨大防衛拠点へ変貌させた。極限状況下での生存モデルの先駆者となった。",
            "「農も商も、すべてが障壁のためだ——だが、組織的絶滅だけは回避した。」",
            "防衛特化型経済の確立。",
            "「文明の多様性を切り捨ててでも、生存を選んだ。」",
            "東端に立つ巨大障壁の結晶光。",
            "「千年史における東方生存モデルの原型が完成した。」",
            "防衛特化モデルボーナス。",
            month=3, day=14, hour=12,
            hist_suffix="EAST_FORTRESS_MODEL",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_BARRIER_STEP_04", level=11,
        ),
    ],
    21: [
        world_evt(
            21, "MonsterAttack", "monster",
            "【全世界】で第2章が始まり、暫定防衛体制が耐用年数の限界に達した。",
            "ターン21（210年目）時点で生存国家は百十前後を維持していたが、初期大崩壊時代に構築された暫定防衛体制が耐用年数の限界を迎え、生存能力の有無で命運が分かれる過激な淘汰期が始まった。",
            "「十年使い続けた壁が、同時にひび割れ始めた。」",
            "防衛体制の老朽化。淘汰の過激化。",
            "「生き残るか、消えるか——中間はもうない。」",
            "各地で同時に揺らぐ防衛線。",
            "「第2章——瓦解と鉄血の同盟の時代が始まった。」",
            "第2章開始ボーナス。",
            month=1, day=10, hour=8,
            hist_suffix="CHAPTER_TWO_ONSET",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_16", level=12,
        ),
        world_evt(
            21, "MagicPioneering", "domestic",
            "【全世界】で耕作地放棄と都市過密集中が同時多発した。",
            "防衛リソースの限界から広域領土の維持が事実上不可能となり、多くの地域で耕作地の完全放棄と主要都市への過密人口集中が同時多発。生存領域は数分の1に縮小したが、防衛線密度は高まった。",
            "「畑は捨てろ。人は城の中へ——壁の内側だけが世界だ。」",
            "耕作地放棄。都市過密化。",
            "「空間を捨てて密度を買う——第2章の基本原則が始まった。」",
            "外周の放棄された畑と、過密な内周都市。",
            "「領土は小さくなった。だが、壁は厚くなった。」",
            "過密集中ボーナス。",
            month=9, day=4, hour=15,
            hist_suffix="URBAN_OVERCONCENTRATION",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_17", level=12,
        ),
    ],
    22: [
        world_evt(
            22, "MonsterAttack", "monster",
            "【西方外周】で脆弱統治体の組織崩壊が相次いだ。",
            "ターン22（220年目）前後、西方外周の脆弱統治体が防衛線決壊により組織的統治能力を喪失。生存能力の有無による淘汰が西方から内側へ波及し始めた。",
            "「西方の外周から、統治の色が次々と消える。」",
            "西方外周の連鎖崩壊。",
            "「暫定防衛の限界が、地図に刻まれ始めた。」",
            "西方に広がる無主地帯。",
            "「淘汰は加速する。」",
            "西方連鎖崩壊ボーナス。",
            month=4, day=19, hour=11,
            hist_suffix="WEST_PERIPHERY_COLLAPSE",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_02", level=12,
        ),
    ],
    23: [
        world_evt(
            23, "MagicPioneering", "domestic",
            "【全世界】で国際交易路が完全に途絶した。",
            "構造淘汰の代償として地域間の交易路は完全に途絶。国際的な互助関係や技術交流は過去のものとなり、各国は自国内資源と限られた固有技術のみで隔絶された防衛戦を継続することとなった。",
            "「街道はもう繋がらない。隣国の結晶塔は見えない。」",
            "交易完全途絶。国際隔離。",
            "「鉄血の同盟は、まだ生まれていない——今は孤独な要塞の時代だ。」",
            "途絶えた交易路と沈黙の国境。",
            "「隔絶された防衛戦が、数世代続く。」",
            "交易途絶デバフ。",
            month=7, day=12, hour=9,
            hist_suffix="TRADE_TOTAL_SEVERANCE",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_CYCLE_STEP_18", level=12,
        ),
    ],
    24: [
        world_evt(
            24, "ShieldFortification", "domestic",
            "【全世界】で軍政一体化が残存国家に標準装備された。",
            "ターン24（240年目）前後、残存国家は資源配給制と軍事内政の一体化をさらに進め、防衛特化型の組織構造へ変容。暫定体制の修繕ではなく、制度そのものの再設計が始まった。",
            "「議会は軍議になった。配給票は弾薬と結晶と同じ帳簿だ。」",
            "軍政一体化の深化。",
            "「国家は、全員が防衛者になった。」",
            "軍議と配給所が一体化した都市。",
            "「鉄血の内政へ向かう。」",
            "軍政一体ボーナス。",
            month=11, day=6, hour=14,
            hist_suffix="MILITARY_CIVIC_FUSION",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_19", level=13,
        ),
    ],
    25: [
        world_evt(
            25, "MonsterAttack", "monster",
            "【全世界】で生存国家数が百五前後まで凋落した。",
            "ターン25（250年目）を過ぎる頃、人類総国力はさらに減退し、生存国家数はついに百五前後へ凋落。暫定防衛体制の限界を超え、文字通り生存能力の有無で命運が分かれる時期となった。",
            "「百十の灯火が、百五に減った。消えた五つは、壁が薄かったからだ。」",
            "百五カ国への凋落。",
            "「淘汰は、まだ終わらない。」",
            "地図から消えた五つの領域。",
            "「第3世紀前半の底を見始めた。」",
            "百五凋落ボーナス。",
            month=3, day=22, hour=7,
            hist_suffix="HUNDRED_FIVE_DECLINE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_20", level=13,
        ),
        nation_ref_evt(
            "NATION_015", 25, "LocalConflict", "conflict",
            "【西方大陸南部】が最西端統合圏の領域再編に真っ向から反発した。",
            "急速に進む統合圏の強硬な領域再編に対し、南方の有力国家が結晶地帯と防衛権を巡って真っ向から反発。人間同士の生存権をかけた領域再編の摩擦が生じた。",
            "「統合の使者を帰せ。南方の結晶地帯は我らの軍政圏だ。」",
            "対抗軸の台頭。",
            "「表向きは交渉、裏では防衛線が増強されている。」",
            "南方境界に増設された結晶塔。",
            "「二極化の第一声が上がった。」",
            "反発衝突ボーナス。",
            month=2, day=28, hour=18,
            hist_suffix="SOUTH_COUNTER_AXIS",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_01", level=13,
        ),
        nation_ref_evt(
            "NATION_002", 25, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】で高密度障壁網の慢性的出力低下が確認された。",
            "長引く高脅威周期により国内資源の枯渇が深刻化。誇る高密度エネルギー障壁網の各所で慢性的な出力低下が確認され、焦土戦術以前の致命的危機が表面化した。",
            "「障壁の光が弱まっている。結晶基盤は疲弊している——次の一手が必要だ。」",
            "障壁出力の慢性低下。",
            "「外周を焼くか、内周を捨てるか——選択が迫られる。」",
            "明滅する東端の障壁網。",
            "「焦土戦術への道が開かれ始めた。」",
            "障壁疲弊デバフ。",
            month=8, day=3, hour=20,
            hist_suffix="BARRIER_OUTPUT_DECLINE",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_BARRIER_STEP_05", level=13,
        ),
    ],
    26: [
        nation_ref_evt(
            "NATION_001", 26, "LocalConflict", "conflict",
            "【最西端の統合王国】が吸収統合政策をさらに加速させた。",
            "周辺の脆弱小国群が脅威の前に瓦解する中、統合中核は統治権と固有エネルギー結晶基盤を冷徹に自国へ組み込む広域統合政策を加速。領域・西の政治地図が最も激しく動いた。",
            "「崩れた国の結晶炉は、我らの配給網に接続する。拒否すれば、壁の外だ。」",
            "吸収統合の加速。",
            "「弱小諸国が統合システムへ吸い込まれていく。」",
            "拡大する統合圏の配線色。",
            "「絶対防衛圏への道が開かれた。」",
            "吸収加速ボーナス。",
            month=5, day=15, hour=10,
            hist_suffix="ABSORPTION_ACCELERATION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_04", level=13,
        ),
        world_evt(
            26, "MonsterAttack", "monster",
            "【西方内陸】で統合圏外の脆弱拠点が面的侵攻に崩れた。",
            "統合圏の拡大と並行し、まだ吸収されていない西方内陸の脆弱拠点が面的侵攻により次々と組織的統治能力を喪失。統合圏の軍事介入対象が増加した。",
            "「統合の使者が来る前に、前線が消える——残るのは難民だけだ。」",
            "統合圏外の連鎖崩壊。",
            "「崩壊地は、統合圏の餌食になる。」",
            "崩壊した前線と向かう統合軍の影。",
            "「冷徹な吸収の時代が加速した。」",
            "統合圏外崩壊ボーナス。",
            month=10, day=27, hour=16,
            hist_suffix="PRE_INTEGRATION_COLLAPSE",
            related="NATION_001",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_03", level=13,
        ),
    ],
    27: [
        nation_ref_evt(
            "NATION_015", 27, "LocalConflict", "conflict",
            "【西方大陸南部】が残存小国と共同防衛協定を締結し対抗軸を固めた。",
            "統合圏の急激な肥大化に対し、南方有力国は周辺の残存小国と独自の共同防衛協定を締結。明確な対抗軸として台頭し、国内の軍事統制を極限まで高めた。",
            "「小さな旗は、大きな旗の下に集まれ。結晶地帯を守るなら、共に壁を張れ。」",
            "共同防衛協定の締結。",
            "「対抗軸の第二環が完成した。」",
            "南方に連なる共同防衛線。",
            "「人間の社会秩序のリアリズムが、統合を遅らせる。」",
            "共同防衛ボーナス。",
            month=8, day=11, hour=13,
            hist_suffix="JOINT_DEFENSE_PACT",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_02", level=14,
        ),
        nation_ref_evt(
            "NATION_008", 27, "MonsterRepelled", "monster",
            "【西方大陸中央の河川要塞帯】が河川防衛で侵攻を撃退し中核拠点の地位を固めた。",
            "統合圏の拡大と並行し、河川防衛要塞群を盾に面的侵攻を撃退。中央部の中核拠点としての信頼を固め、統合圏との摩擦の土台となる軍事的存在感を確立した。",
            "「奴らは泳げない。大河が我らの城壁だ。」",
            "河川防衛の勝利。",
            "「周辺小国は要塞網に組み込まれ始めた。」",
            "河上に砲撃の跡。切断された橋。",
            "「有力国としての地位が、統合圏に警戒をさせた。」",
            "河川撃退ボーナス。",
            month=6, day=24, hour=18,
            hist_suffix="RIVER_FORTRESS_VICTORY",
            zone="ZONE_WEST_RIVER_FORTRESS", mmo_flag="MMO_ZONE_WEST_RIVER_STEP_01", level=13,
        ),
    ],
    28: [
        nation_ref_evt(
            "NATION_001", 28, "LocalConflict", "conflict",
            "【最西端の統合王国】が崩壊地への冷徹な軍事介入を開始した。",
            "ターン28（280年目）から周辺の脆弱統治体が内政崩壊や防衛線決壊により組織的能力を喪失する中、統合圏は崩壊地に冷徹な軍事介入を行い、生存住民と残存結晶基盤を自国管理下に組み入れた。",
            "「崩壊地に軍を入れる。抵抗は鎮圧、結晶は接収、住民は配給網へ。」",
            "崩壊地への軍事介入。",
            "「救済ではない——吸収だ。」",
            "統合軍の旗が崩壊地に立つ。",
            "「領域・西の覇権争いが、新たな段階へ入った。」",
            "軍事介入ボーナス。",
            month=3, day=7, hour=6,
            hist_suffix="COLLAPSE_ZONE_INTERVENTION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_05", level=14,
        ),
        world_evt(
            28, "LocalConflict", "conflict",
            "【西方諸国間】で安全圏確保を巡る局地衝突が表面化した。",
            "統合圏の急速な巨大化に対し、同領域の有力防衛拠点が警戒を強め、限られた安全な生存領域や特異地帯の占有権を巡り、水面下および局地的な武力衝突を含む鋭い対立が展開された。",
            "「安全圏は一つしかない——誰が中に入り、誰が外に出る。」",
            "安全圏を巡る局地衝突。",
            "「脅威が周囲を遊弋する中、人間同士が争う。」",
            "境界で交わされる結晶砲の光。",
            "「鉄血の同盟の前に、鉄血の摩擦がある。」",
            "局地衝突ボーナス。",
            month=11, day=18, hour=20,
            hist_suffix="SAFE_ZONE_FRICTION",
            related="NATION_001",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_04", level=14,
        ),
    ],
    29: [
        world_evt(
            29, "ShieldFortification", "domestic",
            "【西方諸国】で防衛リソースの高度集約が進み複合国家へ移行し始めた。",
            "人間同士の覇権と生存闘争の結果、弱小小国群が統合圏を中心とする強固な統治システムへ吸収され始めた。領域・西は乱立諸国の時代から少数の強力な複合国家による絶対防衛圏の時代へ移行し始めた。",
            "「小さな旗は消え、大きな壁だけが残る。」",
            "複合国家への移行開始。",
            "「防衛リソースの高度集約が、西方の新秩序を作る。」",
            "統合された巨大防衛網の光。",
            "「絶対防衛圏の時代が、地平線に見え始めた。」",
            "複合国家ボーナス。",
            month=4, day=25, hour=11,
            hist_suffix="COMPOUND_STATE_TRANSITION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_WORLD_WEST_STEP_05", level=14,
        ),
    ],
    30: [
        world_evt(
            30, "MagicPioneering", "domestic",
            "【全世界】で空間放棄と密度交換の原則が残存国家の共通言語になった。",
            "ターン30（300年目）前後、人類は莫大な領土と人口を喪失した代わりに、残存領域の防衛密度を極限まで高める構造を体得した。空間の放棄と密度の交換という生存の基本原則が、各地の残存国家の共通言語となった。",
            "「広さを捨て、厚さを取れ——それが、この時代の唯一の数学だ。」",
            "空間放棄・密度交換の原則確立。",
            "「次なる200年を生き抜くための冷徹な国家システムが形になりつつある。」",
            "縮小されたが厚い防衛圏の地図。",
            "「第2章前半の終わり——常夜の底への準備が整いつつある。」",
            "密度交換ボーナス。",
            month=12, day=8, hour=17,
            hist_suffix="SPACE_DENSITY_EXCHANGE",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_21", level=14,
        ),
        nation_ref_evt(
            "NATION_001", 30, "ShieldFortification", "domestic",
            "【最西端の統合王国】が領域西における絶対防衛圏の原型を確立した。",
            "弱小小国群の吸収が進み、統合圏を中心とする強固な統治システムが領域・西の新秩序の原型となった。後世の大陸統一への明確なマイルストーンが、この時期に築かれた。",
            "「西方の地図で、統合圏の色が周囲を飲み込み始めた。」",
            "絶対防衛圏の原型。",
            "「人間同士の権力集中と領域再編が、次世代の枠組みを決めた。」",
            "西方に広がる統合防衛網の完成形に近い光。",
            "「第2章後半——焦土と常夜への扉が開く。」",
            "絶対防衛圏ボーナス。",
            month=7, day=2, hour=9,
            hist_suffix="ABSOLUTE_DEFENSE_PROTOTYPE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_06", level=14,
        ),
    ],
    31: [
        world_evt(
            31, "MonsterAttack", "monster",
            "【全世界】で第2章後半の淘汰が続き、暫定体制の修繕が限界を超えた。",
            "ターン31（310年目）前後、高脅威周期の継続により生存国家の基盤崩壊が相次ぎ、修繕ではなく制度再設計のみが生き残りの道となった。淘汰は西方・東方の双方で同時進行した。",
            "「壁を直す余裕はない。次に来る波は、直した壁ごと倒す。」",
            "淘汰の継続。体制再設計の必然。",
            "「百五の灯火が、さらに減る前触れがある。」",
            "各地で同時に揺れる防衛線。",
            "「第4世紀への入り口が、血で彩られる。」",
            "後半淘汰ボーナス。",
            month=2, day=16, hour=10,
            hist_suffix="LATE_CH2_ATTRITION",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_22", level=14,
        ),
    ],
    32: [
        world_evt(
            32, "MagicPioneering", "domestic",
            "【東方・中央境界】で国内資源枯渇が国家規模の危機に達した。",
            "ターン32（320年目）前後、領域・東および中央海平原周辺で長引く高脅威周期による国内資源枯渇が深刻化。高密度障壁網の慢性的出力低下が各地で確認され、次の軍事イノベーションへの圧力が高まった。",
            "「結晶庫は底をつく。障壁の光は、もう弱い。」",
            "資源枯渇の深刻化。",
            "「通常の防衛では、次の十年を越えられない。」",
            "明滅する障壁と空の倉庫。",
            "「破滅的な選択への道が開かれた。」",
            "資源枯渇危機デバフ。",
            month=6, day=3, hour=19,
            hist_suffix="RESOURCE_EXHAUSTION_CRISIS",
            zone="ZONE_CENTRAL_SEA_PLAIN", mmo_flag="MMO_WORLD_CENTRAL_STEP_01", level=14,
        ),
        nation_ref_evt(
            "NATION_001", 32, "LocalConflict", "conflict",
            "【最西端の統合王国】が周辺崩壊地の吸収を第2章後半も加速させた。",
            "ターン28以降の軍事介入を経て、統合圏は第2章後半も周辺の崩壊地と残存結晶基盤の吸収を加速。領域・西の覇権構造が少数の複合国家へ収束し続けた。",
            "「まだ地図に色が残るなら、統合の配線を伸ばせ。」",
            "吸収の継続加速。",
            "「絶対防衛圏は、まだ完成していない——だが近づいている。」",
            "拡大する統合圏の配線網。",
            "「西方の地図は、統合の色で塗られつつある。」",
            "吸収継続ボーナス。",
            month=10, day=21, hour=8,
            hist_suffix="INTEGRATION_CONTINUES",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_07", level=14,
        ),
    ],
    33: [
        world_evt(
            33, "MonsterAttack", "monster",
            "【中央海平原】で面的侵攻の波が収まらず防衛線の再設計が迫られた。",
            "ターン33（330年目）前後、中央海平原周辺で脅威個体群の波は収まる気配を見せず、従来の障壁モデルでは突破が相次いだ。防衛線の崩壊を防ぐための最も悲痛な軍事イノベーションが迫られた。",
            "「平原の障壁は紙だ。次の侵攻は、内側まで来る。」",
            "中央平原の防衛危機。",
            "「従来の拒否戦術では、もう足りない。」",
            "平原を越える脅威の影。",
            "「焦土への扉が、開きかけている。」",
            "平原危機ボーナス。",
            month=4, day=14, hour=15,
            hist_suffix="CENTRAL_PLAIN_ASSAULT",
            zone="ZONE_CENTRAL_SEA_PLAIN", mmo_flag="MMO_WORLD_CENTRAL_STEP_02", level=15,
        ),
    ],
    34: [
        world_evt(
            34, "LocalConflict", "conflict",
            "【西方諸国間】で統合圏と対抗軸の冷戦的摩擦が常態化した。",
            "ターン34（340年目）前後、統合圏の肥大化と南方対抗軸の共同防衛網が西方で冷戦的摩擦を常態化。限られた安全圏と資源占有を巡る情報戦と局地衝突が、鉄血の内政を双方に強いた。",
            "「表向きは停戦、裏では結晶塔が増える——西方の日常だ。」",
            "冷戦的摩擦の常態化。",
            "「外敵がいるのに、人間は争う。それが現実だ。」",
            "境界に増設される結晶塔。",
            "「双方の軍事技術が、競い合いながら引き締まる。」",
            "冷戦摩擦ボーナス。",
            month=8, day=27, hour=12,
            hist_suffix="WEST_COLD_FRICTION",
            related="NATION_001",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_06", level=15,
        ),
    ],
    35: [
        world_evt(
            35, "MonsterAttack", "monster",
            "【中央海平原〜東方境界】で焦土エネルギー戦術により死の干渉地帯が形成された。",
            "ターン35（350年目）前後、防衛線外縁の放棄予定地帯で固有エネルギーの暴走による人為的広域破壊が実行された。中央海平原から領域・東にかけての広大な区域が、人間にも脅威個体群にも生存不能な死の干渉地帯へ変貌した。",
            "「外縁を焼け。土も水も空も——何も残すな。進路ごと消せ。」",
            "死の干渉地帯の形成。",
            "「国土の未来を永久に奪う選択——だが、侵攻は鈍った。」",
            "焦土化した平原と歪んだ空気。",
            "「空間と引き換えに時間を買う戦術が、歴史を動かした。」",
            "焦土地帯ボーナス。",
            month=5, day=8, hour=22,
            hist_suffix="SCORCHED_INTERFERENCE_ZONE",
            zone="ZONE_CENTRAL_SCORCHED", mmo_flag="MMO_WORLD_SCORCHED_STEP_01", level=16,
        ),
        nation_ref_evt(
            "NATION_002", 35, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が焦土エネルギー戦術を断行し東方防衛線を死守した。",
            "国内資源枯渇と障壁網の出力低下という致命的危機に対し、放棄予定の外縁領土で固有エネルギーを暴走させ生態系ごと脅威個体群の進路を遮断する焦土エネルギー戦術を断行。自虐的な拒否戦略で東方防衛線を辛うじて維持した。",
            "「外周を焼け。内周だけを残せ——国土の未来は捨て、今を買え。」",
            "焦土エネルギー戦術の断行。",
            "「侵攻の速度が鈍った。代償は、永久に失われた土地だ。」",
            "焦土の向こうに立つ東方の障壁。",
            "「極限状態における軍事イノベーションの完成。」",
            "焦土戦術ボーナス。",
            month=11, day=17, hour=22,
            hist_suffix="SCORCHED_EARTH_TACTICS",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_SCORCHED_STEP_01", level=16,
        ),
        nation_ref_evt(
            "NATION_001", 35, "ShieldFortification", "domestic",
            "【最西端の統合王国】の広域統合システムが防衛と内政を一体化した。",
            "広域統合システムは軍事庇護と結晶流通を同一配線に収束させる統治装置として完成。防衛と内政の完全一体化が進み、絶対防衛圏の組織的基盤が固まった。",
            "「統合された結晶炉は防衛塔でもある。配給と射撃の配線を一本化せよ。」",
            "軍政配線の一体化。",
            "「統合は併合ではなく、組織の進化となった。」",
            "結晶塔が配給所と防衛砲台を兼ねる統合圏。",
            "「西方の鉄血システムが、形を完成させた。」",
            "統合システム完成ボーナス。",
            month=2, day=28, hour=11,
            hist_suffix="INTEGRATION_DEFENSE_FUSION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_08", level=15,
        ),
        nation_ref_evt(
            "NATION_015", 35, "ShieldFortification", "domestic",
            "【西方大陸南部】の分散型拠点網が外縁回収拠点と接続された。",
            "対抗軸としての南方国家は分散型拠点網を外縁回収拠点と接続し、ゲリラ防衛の通信・補給網を一体化。統合圏との長期冷戦の技術的基盤を築いた。",
            "「百の拠点を結晶通信で繋げ。一つが落ちても、網は生き残る。」",
            "分散拠点網の完成。",
            "「対抗軸の技術的脊髄が、南方に張られた。」",
            "南方に細い結晶光の網。",
            "「二極化は、技術でも競い合う。」",
            "分散網接続ボーナス。",
            month=7, day=24, hour=8,
            hist_suffix="DISPERSED_FORTRESS_NET",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_03", level=15,
        ),
    ],
    36: [
        world_evt(
            36, "MonsterRepelled", "monster",
            "【東方焦土帯】で焦土戦術の余波が侵攻速度を劇的に鈍化させた。",
            "焦土エネルギー戦術の余波により、領域・東への面的侵攻速度が劇的に鈍化。死の干渉地帯は人類にとっても脅威にとっても禁足地となったが、東方防衛線の維持に成功した。",
            "「焦土の向こうで、侵攻の波が弱まった。内周は、まだ光っている。」",
            "侵攻速度の鈍化。",
            "「永久に失われた土地の代わりに、十年を買った。」",
            "焦土の境界で弱まる脅威の影。",
            "「拒否戦略が、結果を出した。」",
            "侵攻鈍化ボーナス。",
            month=3, day=19, hour=6,
            hist_suffix="INVASION_SLOWDOWN",
            related="NATION_002",
            zone="ZONE_CENTRAL_SCORCHED", mmo_flag="MMO_WORLD_SCORCHED_STEP_02", level=15,
        ),
    ],
    37: [
        world_evt(
            37, "MagicPioneering", "domestic",
            "【全世界】で焦土戦術の知見が各地の生存国に伝播し始めた。",
            "ターン37（370年目）前後、東方で確立された焦土エネルギー戦術の知見が各地の生存国に伝播。空間を永久に放棄して時間を買う選択肢が、極限防衛の辞書に加わった。",
            "「焼くことで守る——東方が証明した。我らも辞書に書け。」",
            "焦土知見の伝播。",
            "「国土の未来を捨てる戦術が、生存の常識になりつつある。」",
            "各地の作戦室に焦土の設計図。",
            "「軍事イノベーションが、悲劇とセットで広がる。」",
            "焦土知見伝播ボーナス。",
            month=9, day=7, hour=14,
            hist_suffix="SCORCHED_DOCTRINE_SPREAD",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_SCORCHED_STEP_03", level=15,
        ),
    ],
    38: [
        world_evt(
            38, "ShieldFortification", "domestic",
            "【全世界】で鉄血の同盟体制が残存国家の標準構造となった。",
            "ターン38（380年目）前後、生き残った国家はいずれも極めて高度に組織化された軍事内政一体型の構造へ進化。鉄血の同盟と評すべき統治体制が、残存国家の標準となった。",
            "「同盟は優しい言葉だ。実態は、全員が兵士の国家だ。」",
            "鉄血同盟体制の標準化。",
            "「旧態依然の統治は、もう淘汰された。」",
            "軍政一体の都市と配給網。",
            "「第4世紀末が近づく。」",
            "鉄血体制ボーナス。",
            month=11, day=23, hour=10,
            hist_suffix="IRON_BLOOD_ALLIANCE",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_CYCLE_STEP_23", level=16,
        ),
    ],
    39: [
        world_evt(
            39, "MonsterAttack", "monster",
            "【全世界】で第4世紀末の猛攻を前に最終的な体制試練が始まった。",
            "ターン39（390年目）前後、第4世紀末の猛攻を前に残存国家は最終的な体制試練に直面。焦土戦術と統合システムの双方が、常夜の底への入り口で耐えられるか試された。",
            "「四十年の準備は、次の十年で試される。」",
            "体制の最終試練。",
            "「常夜の底が、地平線に見え始めた。」",
            "緊張する防衛線の結晶光。",
            "「第2章の終わりが、迫っている。」",
            "最終試練ボーナス。",
            month=5, day=30, hour=18,
            hist_suffix="PRE_CHAPTER3_TRIAL",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_24", level=16,
        ),
    ],
    40: [
        world_evt(
            40, "MagicPioneering", "domestic",
            "【全世界】で第2章が終わり、生存国家は百前後へ、総国力は約15,630へ急落した。",
            "ターン40（400年目）到達時、生存国家数は約百の大台を割り込み、総国力は15,630付近へ急落。国家数の減少は旧態統治の破棄と複合国家への集約を意味し、人類は空間放棄と密度交換を完全に体得した。",
            "「四百年の終わりに、地図は百の灯火。だが、それぞれの光は鉄血だ。」",
            "第2章完結。百カ国割れ。",
            "「次なる200年——常夜の底——を生き抜くシステムが完成した。」",
            "百年紀の終わりの地図。百の要塞の光。",
            "「第3章——常夜の底——へ。」",
            "第2章完走ボーナス。",
            month=12, day=20, hour=20,
            hist_suffix="CHAPTER_TWO_COMPLETE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_CYCLE_STEP_25", level=17,
        ),
        nation_ref_evt(
            "NATION_001", 40, "ShieldFortification", "domestic",
            "【最西端の統合王国】が絶対防衛圏を確立し第3章への覇権基盤を完成させた。",
            "第2章を通じた吸収統合により、統合圏は領域・西における絶対防衛圏を確立。人間同士の権力集中と領域再編という次世代の政治的枠組みを決定づけ、第3章の覇権基盤を完成させた。",
            "「西方の地図で、統合圏の色が周囲を飲み込んだ。」",
            "絶対防衛圏の確立。",
            "「大陸統一へのマイルストーンが、ここに刻まれた。」",
            "西方に完成した統合防衛網の光。",
            "「常夜の底でも、統合圏は動き続ける。」",
            "絶対防衛圏ボーナス。",
            month=10, day=4, hour=9,
            hist_suffix="ABSOLUTE_DEFENSE_ESTABLISHED",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_09", level=17,
        ),
        nation_ref_evt(
            "NATION_002", 40, "MonsterRepelled", "domestic",
            "【東方の魔導生産大国】が焦土拒否戦略で第4世紀末の猛攻を耐え抜いた。",
            "焦土エネルギー戦術による自虐的拒否戦略を通じて、第4世紀末の猛攻を耐え抜き東方防衛線を維持。空間と引き換えに時間を買う極限戦術が、世界各地の生存国に多大な影響を与えた。",
            "「焼いた土地の向こうで、第4世紀の最後の波を止めた。」",
            "第4世紀末防衛の成功。",
            "「東方の防衛線は、まだ光っている。」",
            "焦土の内側に立つ東方の障壁。",
            "「常夜の底へ向かう東方の拒否戦略が、完成した。」",
            "焦土拒否完走ボーナス。",
            month=6, day=18, hour=22,
            hist_suffix="EAST_SCORCHED_SURVIVAL",
            zone="ZONE_EAST_BARRIER_RING", mmo_flag="MMO_ZONE_EAST_SCORCHED_STEP_02", level=16,
        ),
    ],
    41: [
        world_evt(
            41, "MagicPioneering", "domestic",
            "【全世界】で第3章が始まり、文明の構造的沈降が観測史上最底期に入った。",
            "ターン41（410年目）から第3章が始まり、人類社会全体の構造的沈降が観測史上最底期に入った。高脅威周期の長期化により総国力と生存環境が最底の数値を記録し始め、種の絶滅を拒否するためだけに全活力を消費する時代が幕を開けた。",
            "「進歩は止まった。文明は、ただ生き延びるためだけに動く。」",
            "構造的沈降の開始。",
            "「常夜の底——歴史上最も暗く停滞した時代が始まった。」",
            "灰色に沈む地図と過密な内周都市。",
            "「失伝の古代エネルギー技術が、次々と途絶え始める。」",
            "第3章開始ボーナス。",
            month=1, day=6, hour=7,
            hist_suffix="CHAPTER_THREE_ONSET",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_01", level=17,
        ),
        world_evt(
            41, "MonsterAttack", "monster",
            "【全世界】で高等エネルギー技術の広域継承が不可能になった。",
            "主要都市への過密集中と生産インフラ破壊、都市間物流の永続停止により、高度な固有エネルギー制御技術や障壁修復ノウハウの広域継承が不可能となった。技術者の世代交代に伴う教育体制の破綻が各地で進行した。",
            "「師匠が死ぬ。設計図は焼ける。次の世代には、渡せない。」",
            "古代技術の局所失伝。",
            "「失伝せし古代魔法——エネルギー技術——の時代が始まった。」",
            "焼けた工房と途切れた設計図。",
            "「文明の後退が、不可逆の日常になった。」",
            "技術失伝デバフ。",
            month=9, day=20, hour=14,
            hist_suffix="ANCIENT_TECH_LOSS",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_02", level=17,
        ),
    ],
    42: [
        world_evt(
            42, "ShieldFortification", "domestic",
            "【全世界】で軍事優先型階層社会への硬質化が完了した。",
            "ターン42（420年目）前後、残存国家の社会構造は完全なる軍事優先型階層社会、または生存配給制を基盤とする閉鎖的統治体へ硬質化。余剰生産の概念は消滅し、すべての人間は防衛戦力またはエネルギー生産リソースとして計算された。",
            "「生まれた瞬間から番号が振られる。兵士か、炉か——それ以外はない。」",
            "軍事優先型社会の確立。",
            "「種の絶滅を拒否するためだけに、全活力を消費する。」",
            "配給所と軍議が一体化した都市。",
            "「暗黒時代の社会構造が、固まった。」",
            "階層社会ボーナス。",
            month=5, day=14, hour=11,
            hist_suffix="MILITARY_CASTE_SYSTEM",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_03", level=17,
        ),
    ],
    43: [
        world_evt(
            43, "MonsterAttack", "monster",
            "【全世界】で脅威度1.05超の猛攻が長期化し局所密度維持のみが生存手段となった。",
            "ターン43（430年目）前後、脅威個体群の平均脅威度は依然1.05超の猛攻水準を維持。人類は広域の喪失と引き換えに局所的密度の維持のみで生存を繋ぐ状況に追い込まれた。",
            "「広い土地は捨てた。厚い壁だけが、まだ残っている。」",
            "局所密度維持による生存。",
            "「最底期の数字が、記録され続ける。」",
            "過密な内周と外側の暗闇。",
            "「耐え難きを耐える時代が、続く。」",
            "猛攻長期化デバフ。",
            month=8, day=2, hour=16,
            hist_suffix="THREAT_ABOVE_105",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_04", level=18,
        ),
    ],
    44: [
        world_evt(
            44, "MagicPioneering", "domestic",
            "【最西端統合圏周辺】で絶対防衛線の維持限界が表面化し始めた。",
            "ターン44（440年目）前後、前章で巨大化した統合圏は広域防衛能力の限界値に直面。外縁防衛線を構成する拠点が脅威個体群の波状攻撃で機能不全に陥り始め、厳しい選択が迫られた。",
            "「外周の塔が次々と沈黙する。内周へ——それしかない。」",
            "絶対防衛線の限界。",
            "「生存域の選別が、迫っている。」",
            "外周から消える結晶塔の光。",
            "「冷徹な内周収縮の前触れ。」",
            "防衛限界ボーナス。",
            month=3, day=25, hour=9,
            hist_suffix="DEFENSE_LIMIT_SURFACE",
            related="NATION_001",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_10", level=18,
        ),
    ],
    45: [
        nation_ref_evt(
            "NATION_001", 45, "ShieldFortification", "domestic",
            "【最西端の統合王国】が生存域選別のため防衛線を内周へ収縮し外縁を見捨てた。",
            "ターン45（450年目）から外縁防衛拠点が波状攻撃で機能不全に陥る中、統合圏は外周の保護区域と多数の被統合住民を見捨てる形で防衛線を内周へ収縮。中核領域の防衛密度を絶対的に維持する方針を採った。",
            "「外周は捨てる。中核だけを——絶対密度で守れ。」",
            "生存域選別・内周収縮。",
            "「切り捨てられた者たちの信頼は、地図から消えた。」",
            "外周の灰色化と内周の強い結晶光。",
            "「中央集権の冷徹な限界が、表面化した。」",
            "内周収縮ボーナス。",
            month=6, day=11, hour=5,
            hist_suffix="INNER_PERIMETER_ABANDON",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_11", level=18,
        ),
        nation_ref_evt(
            "NATION_015", 45, "LocalConflict", "conflict",
            "【西方大陸南部】が統合圏の外縁放棄領域から残存資源を回収した。",
            "統合圏が防衛線を内周へ縮小した際、南方対抗軸は切り捨てられた外縁領域の生存住民や残存リソースを独自に回収。巨大障壁に頼らない分散型拠点群の拡大が始まった。",
            "「統合圏が捨てた外縁を拾え。住民も結晶炉も、分散網に組み込む。」",
            "外縁回収作戦。",
            "「二極化の地図が、南方に色を増やした。」",
            "放棄領域に立つ南方極の旗。",
            "「ゲリラ防衛網の拡大が始まった。」",
            "外縁回収ボーナス。",
            month=10, day=7, hour=4,
            hist_suffix="OUTER_RIM_RECOVERY",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_04", level=18,
        ),
    ],
    46: [
        world_evt(
            46, "LocalConflict", "conflict",
            "【西方諸国】で超高密度中心要塞圏と分散型拠点群の二極化が成立した。",
            "ターン46（460年目）前後、領域・西は統合圏による超高密度の中心要塞圏と、南方対抗軸を中心とする分散型拠点群という相異なる防衛思想の多極化状態で暗黒時代の底を這うこととなった。",
            "「巨大な壁の国と、百の穴の国——西方には、二つの生き方がある。」",
            "西方二極化の成立。",
            "「全面衝突ではなく、結晶の隠密奪い合いと冷戦が日常だ。」",
            "西方に並ぶ二種類の防衛光。",
            "「相互統制力として、領域全滅を阻いている。」",
            "二極化ボーナス。",
            month=2, day=18, hour=13,
            hist_suffix="WEST_BIPOLAR_ORDER",
            related="NATION_001",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_07", level=18,
        ),
    ],
    47: [
        world_evt(
            47, "MonsterAttack", "monster",
            "【全世界】で暗黒期最大の淘汰波が西方・中央で同時多発した。",
            "ターン47（470年目）前後、暗黒期最大の淘汰波が西方・中央で同時多発。統合圏外の脆弱拠点と中央外周から組織的統治能力の喪失が短期間に集中した。",
            "「一日に六つの統治の色が消えた——最悪の年として記録される。」",
            "暗黒期最大淘汰波。",
            "「生き残る要塞だけが、地図に残る。」",
            "地図に広がる欠番の帯。",
            "「淘汰は、まだ終わらない。」",
            "最大淘汰波ボーナス。",
            month=7, day=29, hour=20,
            hist_suffix="DARK_AGE_MASS_EXTINCTION",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_05", level=19,
        ),
    ],
    48: [
        world_evt(
            48, "MagicPioneering", "domestic",
            "【東方境界】で領土の大半が荒野化し深層魔導都市への移行が始まった。",
            "ターン48（480年目）時点で、焦土戦術の代償により東方大国の領土の八割は磁気嵐と脅威個体群の荒野と化した。主要拠点を地下や遮蔽障壁内部へ隠蔽する深層魔導都市への移行が始まった。",
            "「地表は死んだ。都市は地下へ——坑道の奥に文明を移せ。」",
            "深層魔導都市移行の開始。",
            "「地表の活動指標は、絶滅寸前の灰色に変わった。」",
            "荒廃した地表と坑口から立つ蒸気。",
            "「密閉型生存サイクルの建設が始まった。」",
            "深層移行ボーナス。",
            month=4, day=16, hour=8,
            hist_suffix="DEEP_CITY_TRANSITION",
            related="NATION_002",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_ZONE_EAST_DEEP_STEP_01", level=18,
        ),
        nation_ref_evt(
            "NATION_001", 48, "ShieldFortification", "domestic",
            "【最西端の統合王国】が暗黒期に防衛線を内周へ収縮し資源を死守した。",
            "第3章暗黒期、統合圏は外周拠点を段階的に放棄し防衛線を内周へ収縮。蓄積資源の死守により組織的崩壊を回避し、次の低脅威周期への原動力を温存した。",
            "「外周の結晶塔はもう守りきれない。内周の要塞環に結線を集約せよ。」",
            "資源死守・内周収縮完了。",
            "「収縮は完了した。外周は荒廃地だが、内周の工房は稼働を続ける。」",
            "地図外周の灰色化。内周の強い結晶光。",
            "「反撃の火種を、中核部に温存した。」",
            "収縮防衛ボーナス。",
            month=11, day=5, hour=2,
            hist_suffix="INNER_RETREAT_COMPLETE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_12", level=18,
        ),
    ],
    49: [
        world_evt(
            49, "ShieldFortification", "domestic",
            "【全世界】で孤立要塞国家の点在構造が文明の唯一の形態となった。",
            "ターン49（490年目）前後、かつての世界という広域概念は消滅し、人類文明はいくつかの独立した孤立要塞国家の点在という形でしか存在し得なくなった。",
            "「世界はなくなった。要塞だけが、地図に点として残っている。」",
            "孤立要塞国家の点在。",
            "「連絡は途絶え、互助は過去のものだ。」",
            "点々と立つ要塞の光。",
            "「第5世紀の終わりが近づく。」",
            "孤立要塞ボーナス。",
            month=10, day=23, hour=12,
            hist_suffix="ISOLATED_FORTRESS_ERA",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_06", level=19,
        ),
    ],
    50: [
        world_evt(
            50, "MagicPioneering", "domestic",
            "【全世界】で生存国家数が八十八に減少し、総国力は約12,017へ最底期に達した。",
            "ターン50（500年目）を通過する頃、生存国家数は八十八に減少し、世界全体の総国力は12,017付近という最盛期の約六割に落ち込んだ。人類は局所密度の維持のみで生存を繋ぐ最底期の中間点に立った。",
            "「五百の年目に、灯火は八十八。国力は、六割以下だ。」",
            "八十八カ国・総国力最底。",
            "「それでも、曲線はまだ下がり続ける——だが、要塞は強い。」",
            "八十八の灯火が点す暗い地図。",
            "「常夜の底の中間点——まだ終わりではない。」",
            "最底中間点ボーナス。",
            month=6, day=30, hour=18,
            hist_suffix="MID_DARK_BOTTOM",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_07", level=19,
        ),
        nation_ref_evt(
            "NATION_002", 50, "ShieldFortification", "domestic",
            "【東方の魔導生産大国】が深層魔導都市への移行を完了した。",
            "第3章最底期、東方大国は拠点を地下へ移す深層魔導都市への移行を完了。密閉型生存サイクルで排熱と廃棄魔力を再利用し、文明の失伝を防いだ。",
            "「地表はもう戻らない。坑道の奥に都市を築き、密閉循環で結晶炉を回せ。」",
            "深層魔導都市の完成。",
            "「密閉型生存サイクルが自立した。文明の火種は地下に封じられた。」",
            "地下に青白い都市の光。地表は荒廃。",
            "「極限環境下エネルギー自給技術が、復興のバネとして蓄えられた。」",
            "深層都市完成ボーナス。",
            month=3, day=21, hour=2,
            hist_suffix="DEEP_CITY_COMPLETE",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_ZONE_EAST_DEEP_STEP_02", level=19,
        ),
    ],
    51: [
        world_evt(
            51, "MonsterAttack", "monster",
            "【全世界】で常夜の底の淘汰が続き、孤立要塞間の連絡は完全に断絶した。",
            "ターン51（510年目）前後、第3章最底期の淘汰は続き、孤立要塞国家間の連絡は完全に断絶。エネルギー結晶の隠密奪い合いと生存空間の割当交渉が、西方冷戦の日常となった。",
            "「隣国の結晶塔は見えない。見えるのは、自分の壁だけだ。」",
            "連絡完全断絶。",
            "「冷戦は、高度にシステム化された。」",
            "沈黙する国境と過密な内周。",
            "「耐え難きを耐える——それだけが続く。」",
            "連絡断絶デバフ。",
            month=4, day=9, hour=15,
            hist_suffix="FORTRESS_ISOLATION",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_08", level=19,
        ),
    ],
    52: [
        world_evt(
            52, "ShieldFortification", "domestic",
            "【最西端統合圏】で内周収縮が完了し中核資源の死守が確立した。",
            "ターン52（520年目）前後、統合圏の防衛線内周収縮が完了。外縁拠点の見捨てを経て中核領域の防衛密度が絶対化され、資源の死守体制が確立した。",
            "「外周は灰色の地図になった。内周の炉だけが、まだ燃えている。」",
            "内周収縮完了。",
            "「切り捨てた代償で、中核は守れた。」",
            "内周の強い結晶光と外周の荒廃。",
            "「反撃の火種は、中核に温存された。」",
            "中核死守ボーナス。",
            month=8, day=14, hour=6,
            hist_suffix="INNER_CONTRACTION_COMPLETE",
            related="NATION_001",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_13", level=19,
        ),
        nation_ref_evt(
            "NATION_001", 52, "ShieldFortification", "domestic",
            "【最西端の統合王国】が生存域選別を完遂し統治摩擦の多極化を固定化した。",
            "ターン45から52にかけた内周収縮の完遂により、統合圏は中核資源の死守に成功した一方、切り捨てられた周辺住民や被統合勢力からの信頼を失い、領域内の統治多極化が固定化された。",
            "「中核は守れた。だが、地図の外側は、もう我らの色ではない。」",
            "生存域選別の完遂。",
            "「中央集権の限界と、防衛摩擦が、歴史に刻まれた。」",
            "西方の二色の地図——統合圏と分散網。",
            "「絶対防衛圏の核は、ここに残った。」",
            "選別完遂ボーナス。",
            month=12, day=3, hour=10,
            hist_suffix="SELECTION_ZONE_FIXED",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_14", level=19,
        ),
    ],
    53: [
        world_evt(
            53, "LocalConflict", "conflict",
            "【西方諸国間】で結晶の隠密奪い合いが冷戦の主要手段となった。",
            "ターン53（530年目）前後、西方の二極化構造下で直接的全面武力衝突は避けられ、エネルギー結晶の隠密奪い合いと生存空間の割当交渉が冷戦の主要手段となった。",
            "「正面で撃ち合わない。結晶の輸送路を、裏から切る。」",
            "結晶隠密戦の常態化。",
            "「相互統制力として、領域全滅を阻いている。」",
            "暗い交易路と結晶の黒市。",
            "「人間は、争い方を学習した。」",
            "結晶冷戦ボーナス。",
            month=5, day=27, hour=19,
            hist_suffix="CRYSTAL_COLD_WAR",
            related="NATION_001",
            zone="ZONE_WEST_FRONTIER", mmo_flag="MMO_WORLD_WEST_STEP_08", level=19,
        ),
    ],
    54: [
        nation_ref_evt(
            "NATION_015", 54, "ShieldFortification", "domestic",
            "【西方大陸南部】の分散型拠点網が暗黒期の底でゲリラ防衛を完成させた。",
            "巨大障壁に頼る統合圏とは対照的に、南方対抗軸は地下や高地拠点を基盤とする分散型拠点群で脅威の攻勢を細かく分散・吸収する戦術を完成。暗黒期の底を這いながら領域全滅を阻んだ。",
            "「百の小さな穴で、一つの大波を受け流せ。」",
            "ゲリラ分散防衛の完成。",
            "「超国家的中心要塞だけが、生き残りの手段ではない。」",
            "南方に細く張られた結晶光の網。",
            "「二極化が、西方を生かし続けた。」",
            "ゲリラ網完成ボーナス。",
            month=9, day=16, hour=11,
            hist_suffix="GUERRILLA_NET_COMPLETE",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_05", level=19,
        ),
    ],
    55: [
        world_evt(
            55, "MonsterAttack", "monster",
            "【全世界】で要塞の強度が脅威破壊力を上回る方向へ洗練され始めた。",
            "ターン55（550年目）前後、数世代の防衛生存闘争により、残された要塞の強度は脅威個体群の破壊力を上回る方向へ洗練され始めた。国力減少曲線に横ばいの兆しが混じり始める。",
            "「壁は、もう以前より厚い。奴らの爪は、届きにくくなった。」",
            "要塞強度の洗練。",
            "「後退は、もう許されない構造になった。」",
            "より厚く光る内周の城壁。",
            "「膠着の中に、反転の種が混じる。」",
            "要塞洗練ボーナス。",
            month=2, day=22, hour=8,
            hist_suffix="FORTRESS_OUTPACES_THREAT",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_09", level=20,
        ),
    ],
    56: [
        world_evt(
            56, "ShieldFortification", "domestic",
            "【全世界】で絶対拒否の物理構造が各国の要塞に組み込まれ始めた。",
            "ターン56（560年目）前後、人類の国家システムはこれ以上の後退を許さない絶対拒否の物理構造を組み込み始めた。土地と技術と多様性を失った代わりに、拒否の強度だけは極限まで高まった。",
            "「もう後ろには、何もない。だから、壁は絶対だ。」",
            "絶対拒否構造の組込。",
            "「不屈の膠着状態が、形を取り始める。」",
            "要塞に埋め込まれる拒否の結晶脈。",
            "「第6世紀の終わりが見え始めた。」",
            "絶対拒否ボーナス。",
            month=7, day=8, hour=14,
            hist_suffix="ABSOLUTE_REJECTION_PHYSICS",
            zone="ZONE_WORLD_URBAN_CORE", mmo_flag="MMO_WORLD_DARK_AGE_STEP_10", level=20,
        ),
    ],
    57: [
        world_evt(
            57, "MagicPioneering", "domestic",
            "【全世界】で総国力減少曲線に横ばいの兆しが現れた。",
            "ターン57（570年目）前後、最底付近で人類総国力の減少曲線に緩やかな横ばいの兆しが現れた。脅威度1.05超の環境が長期化しても、要塞の強度向上が下落を食い止め始めた。",
            "「数字は、もう下がりにくい——横ばいの音が聞こえる。」",
            "国力曲線の横ばい。",
            "「最底から、動き始める前触れだ。」",
            "横ばいの地図指標。",
            "「反転の兆し——まだ小さいが、確かだ。」",
            "横ばい兆候ボーナス。",
            month=11, day=30, hour=17,
            hist_suffix="POWER_CURVE_PLATEAU",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_11", level=20,
        ),
    ],
    58: [
        world_evt(
            58, "MonsterAttack", "monster",
            "【東方南部湿地帯】で焦土戦術の慢性余波が限界を超えた。",
            "ターン58（580年目）前後、第2章の焦土エネルギー戦術の環境破壊余波が湿地帯に慢性集中。残留魔力の暴走による磁気嵐で防衛結界の出力結晶基盤が限界を超え、東方外周から組織的統治能力の喪失が進んだ。",
            "「焦土の余波が、二十年遅れて湿地を焼いた。」",
            "焦土余波の限界。",
            "「環境破壊の代償は、長く続く。」",
            "湿地に磁気の残光。",
            "「東方の外周から、また色が消える。」",
            "焦土余波ボーナス。",
            month=3, day=11, hour=19,
            hist_suffix="SCORCHED_FALLOUT_LIMIT",
            related="NATION_002",
            zone="ZONE_EAST_SOUTH_WETLAND", mmo_flag="MMO_WORLD_SCORCHED_STEP_04", level=20,
        ),
    ],
    59: [
        nation_ref_evt(
            "NATION_002", 59, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が密閉型生存サイクルを復興のバネとして深層に蓄積した。",
            "深層魔導都市の密閉型生存サイクルは外部環境に依存しない極限環境下エネルギー自給技術として成熟。地表が脅威の支配下にあっても、都市深層に復興開拓のための技術的バネが蓄えられた。",
            "「地表は死んだ。だが地下の炉は、千年先のために燃えている。」",
            "復興バネの蓄積。",
            "「休眠期が来たとき、この技術が爆発する。」",
            "地下深層に脈打つ結晶炉。",
            "「常夜の底の最後の十年——希望は地下にある。」",
            "復興バネボーナス。",
            month=10, day=5, hour=3,
            hist_suffix="REVIVAL_SPRING_STORED",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_ZONE_EAST_DEEP_STEP_03", level=20,
        ),
    ],
    60: [
        world_evt(
            60, "MagicPioneering", "domestic",
            "【全世界】で第3章が終わり、八十カ国代・総国力最底から横ばいへ転じた。",
            "ターン60（600年目）到達時、独立統治体は八十カ国代に収縮し、総国力12,017付近の底から微動だにせず横ばいと反転の兆しを見せ始めた。絶対拒否の物理構造が完成し、第4章大開拓・復興時代への最大の伏線が張られた。",
            "「六百年の終わりに、灯火は八十。だが、曲線は横を向き始めた。」",
            "第3章完結。最底から横ばいへ。",
            "「耐え難きを耐えた——次は、環境が変わる。」",
            "横ばいの国力曲線と八十の要塞の光。",
            "「第4章——大開拓・復興時代へ。」",
            "第3章完走ボーナス。",
            month=12, day=31, hour=23,
            hist_suffix="CHAPTER_THREE_COMPLETE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_DARK_AGE_STEP_12", level=21,
        ),
        nation_ref_evt(
            "NATION_001", 60, "ShieldFortification", "domestic",
            "【最西端の統合王国】が絶対拒否構造の一翼として中核資源を完全死守した。",
            "第3章を通じた生存域選別と内周収縮により、統合圏は中核資源を完全死守。絶対拒否の物理構造の一翼として、後の大開拓時代の原動力を温存した。",
            "「六百年の暗闇の終わりに、中核の炉はまだ燃えている。」",
            "中核資源の完全死守。",
            "「大開拓の遠征に、十分な備蓄がある。」",
            "内周の結晶光が六百年後も強い。",
            "「西方の反撃の火種は、消えなかった。」",
            "中核死守完走ボーナス。",
            month=6, day=18, hour=9,
            hist_suffix="CORE_RESOURCE_SEALED",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_15", level=21,
        ),
        nation_ref_evt(
            "NATION_015", 60, "LocalConflict", "conflict",
            "【西方大陸南部】が二極化冷戦を維持し第3章を完走した。",
            "統合圏との二極化冷戦を維持し、分散型拠点網で第3章を完走。超国家的中心要塞のみが生存手段ではないことを証明し、西方の全滅を阻ぐ相乗効果を生み続けた。",
            "「六百年、巨大な壁と、百の穴が、互いを生かし続けた。」",
            "二極化冷戦の完走。",
            "「次の章でも、南方の網は残る。」",
            "南方に細く続く結晶光の網。",
            "「多極化こそが、西方を救った。」",
            "二極化完走ボーナス。",
            month=8, day=22, hour=15,
            hist_suffix="BIPOLAR_SURVIVAL",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_06", level=20,
        ),
    ],
    61: [
        world_evt(
            61, "MagicPioneering", "domestic",
            "【全世界】で第4章が始まり、孤立要塞から外向的拡大体制へ舵を切った。",
            "ターン61（610年目）に第4章が始まり、それまで完全循環と極限防衛に特化していた社会構造が、外向的拡大体制へ急激に舵を切った。絶対防衛線の解き放ちと大開拓軍の派遣準備が各地で始まった。",
            "「壁の内側だけが世界だった——今、外へ出る。」",
            "外向的拡大への転換。",
            "「大開拓時代の号令が、各地で上がり始める。」",
            "開く要塞の門と外へ向かう遠征隊。",
            "「第4章——夜明けの鐘と大開拓の号令。」",
            "第4章開始ボーナス。",
            month=1, day=15, hour=8,
            hist_suffix="CHAPTER_FOUR_ONSET",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_01", level=21,
        ),
        world_evt(
            61, "MonsterRepelled", "monster",
            "【全世界】で脅威活動指数の減退兆候が観測され始めた。",
            "ターン61（610年目）前後、約600年間維持された高脅威環境に劇的な変化の兆候が観測され始めた。脅威個体群の活動指数に減退の前触れが混じり、孤立要塞国家が最初に反応した。",
            "「奴らの動きが、鈍くなった——六百年ぶりの気配だ。」",
            "脅威減退の兆候。",
            "「低脅威周期——休眠期——への入り口が見える。」",
            "地平線で弱まる脅威の影。",
            "「環境が、変わり始める。」",
            "脅威減退兆候ボーナス。",
            month=8, day=22, hour=14,
            hist_suffix="THREAT_DECLINE_OMEN",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_02", level=21,
        ),
    ],
    62: [
        world_evt(
            62, "MagicPioneering", "domestic",
            "【全世界】で大開拓軍が未開拓領土と壊滅都市跡へ派遣され始めた。",
            "ターン62（620年目）前後、各国は数世代占有されていた未開拓領土と旧時代の壊滅都市跡へ大開拓軍を次々派遣。領土奪還の号令が単なる拡張を超え、資源採掘再開の始まりとなった。",
            "「外の土地は、まだ我らのものだ——行け、遠征入植部隊。」",
            "大開拓軍の派遣。",
            "「壊滅都市の跡に、旗を立て始める。」",
            "外へ伸びる遠征路と結晶灯。",
            "「失われた版図の再構築が始まった。」",
            "遠征派遣ボーナス。",
            month=5, day=7, hour=10,
            hist_suffix="EXPEDITION_LAUNCH",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_RECOVERY_STEP_03", level=21,
        ),
    ],
    63: [
        nation_ref_evt(
            "NATION_002", 63, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が脅威休眠の兆候を感知し地表解放の準備を始めた。",
            "深層魔導都市は脅威個体群の休眠兆候を感知し、地下に蓄積された技術と人口の地表解放準備を始めた。密閉循環で純化された極限環境対応型エネルギー技術の投入が間近となった。",
            "「地表のセンサーが静かになった。坑道の扉を——準備しろ。」",
            "地表解放準備。",
            "「六百年の地下が、外へ出る。」",
            "地下都市の坑口から立ち上る蒸気。",
            "「深層からの復興が、始まる。」",
            "地表解放準備ボーナス。",
            month=3, day=18, hour=6,
            hist_suffix="SURFACE_RELEASE_PREP",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_ZONE_EAST_DEEP_STEP_04", level=22,
        ),
    ],
    64: [
        world_evt(
            64, "MagicPioneering", "domestic",
            "【全世界】で資源採掘の再開と物流網の再整備が始まった。",
            "ターン64（640年目）前後、大開拓に伴い地表での資源採掘が再開され、途絶していた物流網の再整備が始まった。地域間の経済活動が急速に再興し、総国力のV字回復の足音が聞こえ始めた。",
            "「街道を繋げ。結晶を運べ——六百年ぶりの交易だ。」",
            "採掘再開・物流再整備。",
            "「経済が、再び動き始める。」",
            "復旧する交易路と採掘坑の灯り。",
            "「暗黒時代の底から、上がり始める。」",
            "物流再興ボーナス。",
            month=10, day=11, hour=15,
            hist_suffix="LOGISTICS_REVIVAL",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_RECOVERY_STEP_04", level=22,
        ),
    ],
    65: [
        world_evt(
            65, "MonsterRepelled", "monster",
            "【全世界】で脅威活動指数が1.0未満へ急減し低脅威周期に突入した。",
            "ターン65（650年目）を境界に、脅威個体群の活動指数は1.0未満、さらに0.7台へ急激に減退。低脅威周期（休眠期）への突入を意味し、約600年ぶりの広域的生存環境改善となった。",
            "「脅威度が、一桁の下に落ちた——休眠期だ。」",
            "低脅威周期突入。",
            "「人類にとって、六百年ぶりの夜明けだ。」",
            "弱まる地平線の脅威の影。",
            "「大開拓の黄金期が、本格化する。」",
            "低脅威周期ボーナス。",
            month=6, day=30, hour=12,
            hist_suffix="LOW_THREAT_CYCLE_ONSET",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_05", level=22,
        ),
        nation_ref_evt(
            "NATION_001", 65, "LocalConflict", "conflict",
            "【最西端の統合王国】が蓄積資源を投入し電撃的な対外遠征を開始した。",
            "低脅威周期の到来と同時に、内周死守で温存した膨大な固有エネルギー結晶リソースを対外開拓へ一気に投入。電撃的な対外遠征を開始し、かつて切り捨てた外縁領域の再開拓・再軍備化を敢行した。",
            "「備蓄庫を開け。遠征軍は内周から一斉に外周へ——六百年分の結晶を使え。」",
            "電撃遠征の開始。",
            "「外縁の灰色地図に、再び統合の色が塗られ始める。」",
            "統合圏から外へ伸びる遠征路の結晶灯。",
            "「一極支配の礎が、動き始めた。」",
            "電撃遠征ボーナス。",
            month=7, day=15, hour=14,
            hist_suffix="LIGHTNING_EXPEDITION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_16", level=23,
        ),
    ],
    66: [
        world_evt(
            66, "MagicPioneering", "domestic",
            "【全世界】で総国力のV字回復が本格化した。",
            "ターン66（660年目）前後、総国力は暗黒時代の底12,017付近から本格的なV字回復に入った。大開拓と資源再開により、世代を超えて耐え忍んだ人類が失われた文明版図の再構築を加速した。",
            "「国力の曲線が、上を向いた——六百年ぶりの上昇だ。」",
            "V字回復の本格化。",
            "「黄金期の足音が、確かに聞こえる。」",
            "上昇する地図指標と復興する街道。",
            "「大開拓時代の真っただ中だ。」",
            "V字回復ボーナス。",
            month=4, day=8, hour=9,
            hist_suffix="V_SHAPE_RECOVERY",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_06", level=22,
        ),
    ],
    67: [
        nation_ref_evt(
            "NATION_002", 67, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が深層から人口と技術を地表へ一気に解放した。",
            "脅威休眠を確認した東方大国は、地下に蓄積されたすべての技術と人口を地表へ一気に解放。極限環境対応型固有エネルギー技術が焦土の爪痕への投入準備を完了した。",
            "「坑道の扉を開け。全員、地表へ——技術も人口も、六百年分を持ち出せ。」",
            "深層からの全面解放。",
            "「灰色だった活動指標が、熱を帯び始める。」",
            "坑口から溢れる人と技術の光。",
            "「地表復興が、本格始動した。」",
            "深層解放ボーナス。",
            month=11, day=2, hour=8,
            hist_suffix="DEEP_TO_SURFACE_RELEASE",
            zone="ZONE_EAST_UNDERGROUND", mmo_flag="MMO_ZONE_EAST_DEEP_STEP_05", level=23,
        ),
        world_evt(
            67, "MagicPioneering", "domestic",
            "【中央海平原】で焦土跡の環境浄化が始まった。",
            "ターン67（670年目）前後、東方の極限環境対応技術により、かつて焦土戦術で不毛地と化した中央海平原の環境浄化が始まった。エネルギー結晶鉱山の急速再開発の足場が整った。",
            "「焦土の跡に、緑の芽が——技術が、土地を取り戻す。」",
            "焦土跡の浄化開始。",
            "「不毛だった平原が、資源地に変わり始める。」",
            "荒野に戻り始める緑と採掘坑。",
            "「魔導大国の復興色が、地図を塗る。」",
            "環境浄化ボーナス。",
            month=2, day=25, hour=13,
            hist_suffix="SCORCHED_LAND_RECLAMATION",
            related="NATION_002",
            zone="ZONE_CENTRAL_SEA_PLAIN", mmo_flag="MMO_WORLD_CENTRAL_STEP_03", level=22,
        ),
    ],
    68: [
        nation_ref_evt(
            "NATION_015", 68, "LocalConflict", "conflict",
            "【西方大陸南部】が統合圏の圧倒的物量の前に主導権を譲り自治を交渉した。",
            "環境好転で分散防衛の優位を失った南方対抗軸は、統合王国の圧倒的な開拓速度と物量の前に主導権を譲った。広域統治体制下への組み込みを交渉で進め、軍事伝統の温存を確保した。",
            "「軍事では敗れた。だが形式と軍事伝統は死守する——条約に明記しろ。」",
            "主導権譲渡と自治交渉。",
            "「軟着陸条約が調印された。南方だけ、異なる軍旗が残る。」",
            "統合圏の色の中に残る南方の軍旗。",
            "「二極冷戦に、終止符が近づく。」",
            "軟着陸交渉ボーナス。",
            month=9, day=3, hour=13,
            hist_suffix="SOUTH_SOFT_LANDING",
            related="NATION_001",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_SOUTH_STEP_07", level=23,
        ),
    ],
    69: [
        world_evt(
            69, "MagicPioneering", "domestic",
            "【全世界】で大陸間連絡ルートが約六百年ぶりに再開された。",
            "ターン69（690年目）前後、世界各地の開拓網により海上および陸上の大陸間連絡ルートが約600年ぶりに再開。世界は再び一つの相互作用圏としての形を取り戻し始めた。",
            "「海を渡れ。街道を繋げ——世界は、また一つになる。」",
            "大陸間連絡再開。",
            "「相互作用圏の復活が、交易を爆発させる。」",
            "海と陸に復活する交易路。",
            "「孤立要塞の時代は、終わりつつある。」",
            "連絡再開ボーナス。",
            month=7, day=19, hour=16,
            hist_suffix="INTERCONTINENTAL_ROUTES",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_RECOVERY_STEP_07", level=23,
        ),
    ],
    70: [
        world_evt(
            70, "MagicPioneering", "domestic",
            "【全世界】で二大勢力圏の並立が第4章前半の頂点となった。",
            "ターン70（700年目）時点で、領域・西の統合王国による一極拡大と、領域・東の魔導大国による地表復興が並立。共通の敵が沈黙した世界で、人類が領域の支配者へ脱皮し始めた。",
            "「西方に統合の太陽、東方に魔導の炉——二つの極が、地図を照らす。」",
            "二大勢力圏の並立。",
            "「覇権のための統合が、生存のための統合を超え始める。」",
            "西方と東方に立ち上がる二種類の光。",
            "「第5章へのチェス盤が、並べられ始めた。」",
            "二極並立ボーナス。",
            month=12, day=10, hour=18,
            hist_suffix="DUAL_POLE_EMERGENCE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_08", level=24,
        ),
        nation_ref_evt(
            "NATION_002", 70, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が脅威素材を資源化する魔導工学を確立した。",
            "極限環境で純化された結晶技術が低脅威周期で魔導工学へ昇華。大人しくなった脅威個体群の残存素材をエネルギー源や触媒として回収・再利用する新技術体系を確立した。",
            "「殻虫の外骨格は最高級の触媒だ。恐れるな、炉に入れろ。」",
            "魔導工学の確立。",
            "「脅威は敵ではなく、資源になった。」",
            "魔導工場の煙突と浄化された荒野。",
            "「コペルニクス的転換——文明の糧へ。」",
            "魔導工学ボーナス。",
            month=6, day=10, hour=11,
            hist_suffix="ARCANE_ENGINEERING",
            zone="ZONE_EAST_FORGE_BELT", mmo_flag="MMO_ZONE_EAST_FORGE_STEP_06", level=24,
        ),
    ],
    71: [
        nation_ref_evt(
            "NATION_001", 71, "LocalConflict", "conflict",
            "【最西端の統合王国】が外縁拠点群の経済圏・軍事統制への組み込みを本格化した。",
            "ターン70以降、統合王国は電撃遠征の成果を踏まえ外縁の小規模生存拠点群を次々と経済圏・軍事統制下へ組み込むプロセスを本格化。覇権のための統合が生存のための統合を超え始めた。",
            "「傘下に入れ。拒む者には局所制圧——だが大半は生産力の共有を選ぶ。」",
            "外縁統合の本格化。",
            "「西方の地図が、一色に塗られ始める。」",
            "統合圏の色が外縁へ広がる。",
            "「一極支配の歯車が、回り始めた。」",
            "外縁統合ボーナス。",
            month=2, day=20, hour=11,
            hist_suffix="PERIPHERY_INTEGRATION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_17", level=24,
        ),
        world_evt(
            71, "MagicPioneering", "domestic",
            "【全世界】で大開拓の副産として外縁独立宣言が相次いだ。",
            "ターン71（710年目）前後、最西端統合圏の外縁再開拓の影で開拓民コミュニティによる独立宣言が各地で相次いだ。国数は一時的に上振れ、幻の国家が歴史に現れ始めた。",
            "「障壁が再点灯した——統合の旗を降ろせ、と叫ぶ声が外縁に響く。」",
            "外縁独立宣言の波。",
            "「新生国家の灯りが、地図に一時的に増える。」",
            "外縁地に立つ新しい結晶灯。",
            "「発展的統合の時代にも、反発の火花は散る。」",
            "独立宣言波ボーナス。",
            month=8, day=5, hour=15,
            hist_suffix="FRONTIER_INDEPENDENCE_WAVE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_09", level=24,
        ),
    ],
    72: [
        nation_ref_evt(
            "NATION_004", 72, "MagicPioneering", "domestic",
            "【極寒針葉樹林の前線】が希少エネルギー結晶の独占供給を開始した。",
            "第4章復興期、蓄積された採掘技術で北方の希少エネルギー結晶の独占供給を開始。大国の版図拡大にも飲み込まれない資源権益を確立し、独立の籠城として交渉力を維持した。",
            "「希少結晶の採掘量は我らだけが握っている。買いたければ、価格は我らが決める。」",
            "独占供給の開始。",
            "「統合王国も魔導大国も、我らの結晶を求めている。」",
            "採掘坑道から結晶輸送路が延びる。",
            "「小国だが、替えがたい。」",
            "独占供給ボーナス。",
            month=4, day=12, hour=9,
            hist_suffix="CRYSTAL_MONOPOLY",
            zone="ZONE_NORTH_CRYSTAL_EXPORT", mmo_flag="MMO_ZONE_NORTH_EXPORT_STEP_02", level=24,
        ),
        nation_ref_evt(
            "NATION_007", 72, "MagicPioneering", "domestic",
            "【東方内陸の山岳要塞帯】が東方魔導大国の共同再興圏に希少結晶素材を供給した。",
            "大開拓時代、東方魔導大国が主導する共同再興圏に対し、山岳鉱山の希少結晶素材を提供。経済パートナーシップを早期に締結し、軍事征服を回避した。",
            "「山の鉱脈は我らの交渉カードだ。再興圏に素材を売れば、征服は避けられる。」",
            "再興圏への供給契約。",
            "「希少結晶の定期輸送が東へ伸びる。」",
            "山岳坑道から輸送索道が東へ延びる。",
            "「経済で独立を買った。」",
            "供給契約ボーナス。",
            related="NATION_002",
            month=6, day=25, hour=10,
            hist_suffix="MOUNTAIN_SUPPLY_PACT",
            zone="ZONE_EAST_MOUNTAIN_FORTRESS", mmo_flag="MMO_ZONE_EAST_MOUNTAIN_STEP_03", level=24,
        ),
    ],
    73: [
        world_evt(
            73, "MonsterAttack", "monster",
            "【全世界】で幻の外縁国家が脆弱な防衛で次々と瓦解した。",
            "ターン73（730年目）前後、短命の外縁独立国家は防衛出力の長期維持に失敗し、統合圏の圧力と残存脅威の突発攻勢の前に次々と瓦解。発展的統合の時代における淘汰の第一波となった。",
            "「再点灯した障壁が、二年で消えた——幻の国家は、幻のまま終わる。」",
            "幻の国家の瓦解。",
            "「独立宣言の灯りが、地図から消えていく。」",
            "消えゆく外縁の結晶灯。",
            "「強国への傘下が、生存の現実解になる。」",
            "幻国瓦解ボーナス。",
            month=11, day=18, hour=7,
            hist_suffix="PHANTOM_STATE_COLLAPSE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_10", level=24,
        ),
    ],
    74: [
        nation_ref_evt(
            "NATION_001", 74, "LocalConflict", "conflict",
            "【最西端の統合王国】が拒否勢力への局所制圧と傘下交渉を並行した。",
            "外縁統合の加速に伴い、統合圏への組み込みを拒む勢力に対する局所的武力制圧と、生産力共有を条件とした傘下交渉が並行して進行。領域・西の政治的単一化が着実に前進した。",
            "「拒む者には結晶弾、従う者には糧と盾——選択は一つだ。」",
            "局所制圧と傘下交渉。",
            "「小規模拠点の色が、統合の一色に変わる。」",
            "地図上で消えゆく独立の色。",
            "「西方統一の歯車が、加速する。」",
            "統合加速ボーナス。",
            month=5, day=28, hour=13,
            hist_suffix="LOCAL_SUPPRESSION_PACT",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_18", level=25,
        ),
        world_evt(
            74, "NationBirth", "lifecycle",
            "【全世界】で東方辺境に開拓民による新生国家宣言が相次いだ。",
            "ターン74（740年目）前後、東方辺境平野部でも廃棄結晶炉の再起動と防衛障壁の復活により開拓民コミュニティによる独立宣言が相次いだ。西方と同様、短命国家の誕生と滅亡のサイクルが始まった。",
            "「平野に障壁が再点灯した——ここも、幻の国になるのか。」",
            "東方辺境の新生国家。",
            "「国数は再び一時的に上振れる。」",
            "辺境平野に立つ新しい灯り。",
            "「大開拓の副産物——幻の国家の連鎖。」",
            "辺境誕生ボーナス。",
            month=9, day=14, hour=16,
            hist_suffix="EAST_BORDER_BIRTH_WAVE",
            zone="ZONE_EAST_BORDER_PLAIN", mmo_flag="MMO_WORLD_RECOVERY_STEP_11", level=24,
        ),
    ],
    75: [
        nation_ref_evt(
            "NATION_001", 75, "LocalConflict", "conflict",
            "【最西端の統合王国】が南方対抗軸の本拠周辺を経済圏へ完全統合した。",
            "ターン70から75にかけての統合プロセスの頂点。統合王国は南方対抗軸の本拠および周辺小規模生存拠点群を経済圏・軍事統制下へ完全統合。軟着陸交渉済みの勢力も広域統治体制へ組み込まれた。",
            "「南方極の条約は守る。だが経済と軍事の主導権は、統合圏のものだ。」",
            "南方圏の完全統合。",
            "「領域・西の多元対立に、終止符が打たれる。」",
            "統合圏の色が南方まで一色に。",
            "「巨大な傘の下へ、西方が集まった。」",
            "南方統合ボーナス。",
            related="NATION_015",
            month=3, day=22, hour=14,
            hist_suffix="SOUTH_SPHERE_UNIFICATION",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_19", level=25,
        ),
    ],
    76: [
        world_evt(
            76, "NationBirth", "lifecycle",
            "【全世界】で東方辺境の幻の国家誕生がピークに達した。",
            "ターン76（760年目）前後、東方辺境平野部を中心に開拓民コミュニティによる独立宣言がピークに達した。短命国家の誕生と防衛強化が同時進行し、国数は一時的に最大値へ上振れた。",
            "「平野に灯りが増える——だが、どれも長くは持たない。」",
            "幻の国家誕生のピーク。",
            "「障壁再起動の記録が、各地で重なる。」",
            "辺境に立ち並ぶ短命の結晶灯。",
            "「発展的統合前の、最後の独立の火花。」",
            "誕生ピークボーナス。",
            month=7, day=8, hour=10,
            hist_suffix="PHANTOM_BIRTH_PEAK",
            zone="ZONE_EAST_BORDER_PLAIN", mmo_flag="MMO_WORLD_RECOVERY_STEP_12", level=25,
        ),
    ],
    77: [
        nation_ref_evt(
            "NATION_002", 77, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が領域・東の活動指標を再興の熱量へ塗り替えた。",
            "魔導工学の確立と深層解放の成果が結実し、かつて灰色に沈んでいた領域・東の活動指標は膨大な熱量を示す再興の色へ塗り替えられた。領域・西の統合王国に比肩する世界最強の魔導生産大国としての地位を確立した。",
            "「炉の煙が地平線を染める——東方は、再び燃えている。」",
            "東方全面復興。",
            "「脅威を資源に変える文明が、地図を照らす。」",
            "魔導工場の煙突と浄化された荒野。",
            "「二極のうち、東方の極が完成した。」",
            "魔導大国確立ボーナス。",
            month=10, day=17, hour=12,
            hist_suffix="EAST_REVIVAL_COMPLETE",
            zone="ZONE_EAST_FORGE_BELT", mmo_flag="MMO_ZONE_EAST_FORGE_STEP_07", level=26,
        ),
    ],
    78: [
        world_evt(
            78, "MonsterAttack", "monster",
            "【全世界】で東方辺境の幻の国家が一斉に瓦解した。",
            "ターン78（780年目）前後、東方辺境平野部の短命国家群は残存脅威の突発的大攻勢と防衛インフラの脆弱性露呈により一斉に瓦解。発展的統合の淘汰第二波として、強国への版図吸収が加速した。",
            "「平野の灯りが、一夜にして消えた——幻の国家の冬が来た。」",
            "幻の国家一斉瓦解。",
            "「防衛出力の長期維持に失敗した国家が、地図から消える。」",
            "消えゆく辺境の障壁。",
            "「淘汰ではなく、発展的吸収の時代。」",
            "一斉瓦解ボーナス。",
            month=4, day=19, hour=20,
            hist_suffix="PHANTOM_MASS_EXTINCTION",
            zone="ZONE_EAST_BORDER_PLAIN", mmo_flag="MMO_WORLD_RECOVERY_STEP_13", level=25,
        ),
    ],
    79: [
        world_evt(
            79, "MagicPioneering", "domestic",
            "【全世界】で生存国家数が発展的統合により約七十前後へ集約された。",
            "ターン79（790年目）前後、脆弱な国が脅威に滅ぼされる時代は終わり、強国による版図の吸収と新領域の割当が進行。生存国家数は前章の八十八カ国から約七十前後へと発展的統合により集約された。",
            "「国の数は減った——だが、残った国は強くなった。」",
            "発展的統合による国数集約。",
            "「淘汰ではなく、再編——強国が版図を吸収する。」",
            "地図上の色が濃く、数が減る。",
            "「新たなる大国間対立の土台が、形作られる。」",
            "国数集約ボーナス。",
            month=11, day=30, hour=9,
            hist_suffix="DEVELOPMENTAL_AGGREGATION",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_RECOVERY_STEP_14", level=26,
        ),
    ],
    80: [
        world_evt(
            80, "MagicPioneering", "domestic",
            "【全世界】で第4章が終わり、総国力が一万八千超へ達した。",
            "ターン80（800年目）に第4章が終了。人類全体の総国力は暗黒時代の底を完全に脱し、約18,000ポイント超の領域へ驚異的なV字回復を達成。大陸間連絡ルートの再開と広域物流網により、世界は再び一つの相互作用圏を取り戻した。",
            "「六百年の耐え忍びが、開拓の黄金期へ変わった——国力は、一万八千を超える。」",
            "第4章完結・V字回復達成。",
            "「脆弱国の淘汰は終わり、強国の時代が始まる。」",
            "復興する街道と交易路。",
            "「第5章への導火線が、灯された。」",
            "第4章完結ボーナス。",
            month=12, day=31, hour=23,
            hist_suffix="CHAPTER_FOUR_FINALE",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_RECOVERY_STEP_15", level=27,
        ),
        nation_ref_evt(
            "NATION_001", 80, "MagicPioneering", "domestic",
            "【最西端の統合王国】が領域・西の単一巨大統合王国の完成を宣言した。",
            "ターン80（800年目）を迎え、領域・西における全統治体は統合王国を頂点とする単一の巨大な統合王国へ完全集約。人間同士の長き覇権争いは共通脅威の減退により加速し、かつてない規模の政治的単一秩序が最西端大陸に誕生した。",
            "「西方の地図に、もう二つの色はない——統合の太陽だけが照らす。」",
            "統合王国の完成。",
            "「一極秩序が、最西端大陸に誕生した。」",
            "西方全体を覆う統合の光。",
            "「大遠征への政治・軍事基盤が、完成した。」",
            "統合王国完成ボーナス。",
            month=6, day=1, hour=8,
            hist_suffix="UNIFIED_KINGDOM_COMPLETE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_20", level=27,
        ),
    ],
    81: [
        world_evt(
            81, "MonsterRepelled", "monster",
            "【全世界】で第5章が始まり、脅威活動指数が観測史上最低水準へ沈黙した。",
            "ターン81（810年目）に第5章が開始。世界全体の平均脅威度は0.5という観測史上最低の安定水準へ推移し、低脅威周期（休眠期）が確定的なものとなった。脅威個体群の活性は完全に抑制された。",
            "「脅威度が、半分以下に落ちた——千年で最も静かな世紀だ。」",
            "第5章開始・脅威最低水準。",
            "「休眠期は、もう戻らない。」",
            "地平線にほとんど見えない脅威の影。",
            "「防衛の時代が、攻勢の時代へ変わる。」",
            "第5章開始ボーナス。",
            month=1, day=10, hour=8,
            hist_suffix="CHAPTER_FIVE_ONSET",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_01", level=27,
        ),
        world_evt(
            81, "MagicPioneering", "domestic",
            "【全世界】で孤立要塞国家の時代が完全に終焉した。",
            "ターン81前後、かつての孤立要塞国家の時代は完全に過去のものとなった。地球規模で再接続された強国群は、膨大な余剰生産力と軍政一体型システムを擁する巨大統治体へ変貌し始めた。",
            "「要塞の門は、もう閉じない——外へ、すべてを注げ。」",
            "孤立要塞時代の終焉。",
            "「余剰の結晶と人口が、新たな戦略へ向かう。」",
            "開きっぱなしの要塞の門と遠征の旗。",
            "「生存維持から、完全駆逐へ。」",
            "時代転換ボーナス。",
            month=6, day=22, hour=14,
            hist_suffix="FORTRESS_ERA_END",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_FINALE_STEP_02", level=27,
        ),
    ],
    82: [
        world_evt(
            82, "MagicPioneering", "domestic",
            "【全世界】で総国力の爆発的上昇が第5章前半の基調となった。",
            "ターン82（820年目）前後、人類社会の総国力は爆発的な上昇局面に入った。広域物流網の完全復興と固有エネルギー技術の集約が構造的果実を生み、千年のサバイバルが結実し始めた。",
            "「国力の曲線が、垂直に近づいている——千年の蓄積が、一気に噴き出す。」",
            "総国力の爆発的上昇。",
            "「交易路は、もう途切れない。」",
            "世界中を結ぶ結晶灯の物流網。",
            "「最終世紀の黄金期が、始まった。」",
            "国力上昇ボーナス。",
            month=4, day=15, hour=11,
            hist_suffix="POWER_EXPLOSION",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_FINALE_STEP_03", level=28,
        ),
    ],
    83: [
        nation_ref_evt(
            "NATION_002", 83, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が中央海平原の結晶工業地帯再生を完了した。",
            "最終世紀において魔導大国は地表インフラ復興を完了。かつて焦土戦術で破壊された中央海平原は、世界最高のエネルギー生産性を誇る一大結晶工業地帯へ再生された。",
            "「焦土の記憶が、工業の鼓動に変わった——中央は、世界の炉だ。」",
            "中央海平原の工業地帯完成。",
            "「結晶煙突が平原を覆う。」",
            "中央海平原に立ち並ぶ魔導工場群。",
            "「経済極の足場が、固まった。」",
            "工業地帯完成ボーナス。",
            month=9, day=8, hour=13,
            hist_suffix="CENTRAL_FORGE_COMPLETE",
            zone="ZONE_CENTRAL_SEA_PLAIN", mmo_flag="MMO_WORLD_CENTRAL_STEP_04", level=28,
        ),
    ],
    84: [
        nation_ref_evt(
            "NATION_001", 84, "ShieldFortification", "domestic",
            "【最西端の統合王国】が防衛から攻勢への完全転換を宣言した。",
            "覇権闘争の完了により全リソースを外向的軍事行動へ集中可能となった統合王国は、固有エネルギー資源の配分を防衛から徹底的な攻勢へ完全転換。大遠征への準備が最高統制部レベルで始まった。",
            "「盾はもう十分だ。剣を研げ——脅威を、根から抜く。」",
            "防衛から攻勢への転換。",
            "「結晶兵器庫の封印が、次々と解かれる。」",
            "統合王国の兵器庫から運び出される結晶弾。",
            "「大遠征の号令が、間近に迫る。」",
            "攻勢転換ボーナス。",
            month=2, day=28, hour=10,
            hist_suffix="DEFENSE_TO_OFFENSE",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_01", level=28,
        ),
    ],
    85: [
        nation_ref_evt(
            "NATION_001", 85, "MonsterRepelled", "monster",
            "【最西端の統合王国】が領域・西全域掃討の大遠征を号令した。",
            "ターン85（850年目）から始まる大遠征。統合王国の最高統制部は蓄積されたすべての固有エネルギー兵器と大規模常備軍を動員し、領域・西の全域を面内部から掃討する総力戦を号令した。",
            "「全軍、前進せよ——障壁網を前進させ、巣窟を砕け。」",
            "大遠征の号令。",
            "「散発的防衛ではない。殲滅戦だ。」",
            "前進する空間網羅型エネルギー障壁。",
            "「千年の防衛が、千年の攻勢へ変わる。」",
            "大遠征開始ボーナス。",
            month=3, day=1, hour=6,
            hist_suffix="GREAT_EXPEDITION_LAUNCH",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_02", level=29,
        ),
        nation_ref_evt(
            "NATION_014", 85, "MagicPioneering", "domestic",
            "【北方針葉樹林海】が寒冷圏共同経済同盟で南方統合圧力に対抗した。",
            "極寒針葉樹林前線は北方沿岸の氷結前線と強固な共同経済同盟を結び、南方超大国の領域統合圧力に対抗。自治権と主権を守った。",
            "「北方三極で資源を共有しよう。南方には従わない。」",
            "寒冷圏共同経済同盟。",
            "「森の木材、凍土の結晶、沿岸の海産——北方は一枚岩だ。」",
            "北方に延びる木材・結晶・海産の交易路。",
            "「双極の影で、第三の極が生き残る。」",
            "北方同盟ボーナス。",
            related="NATION_004",
            month=8, day=27, hour=11,
            hist_suffix="NORTH_ALLIANCE",
            zone="ZONE_NORTH_COLD_CIRCLE", mmo_flag="MMO_ZONE_NORTH_COLD_STEP_02", level=28,
        ),
    ],
    86: [
        world_evt(
            86, "MonsterRepelled", "monster",
            "【最西端大陸】で空間網羅型障壁による力学的圧砕戦が進行した。",
            "ターン86（860年目）前後、大遠征は高度な空間網羅型エネルギー障壁を前進させながら脅威個体群の巣窟を力学的に圧砕する徹底殲滅戦の形態をとった。弱体化した脅威個体群は一切の対抗手段を持たず生存領域を喪失した。",
            "「障壁が巣窟を包み、結晶圧で砕く——逃げ場はない。」",
            "力学的圧砕戦。",
            "「脅威の色が、地図から消えていく。」",
            "前進する障壁網の内側で消える脅威の巣。",
            "「完全駆逐への歩みが、加速する。」",
            "圧砕戦ボーナス。",
            month=7, day=14, hour=16,
            hist_suffix="SPATIAL_CRUSHING_WAR",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_03", level=29,
        ),
    ],
    87: [
        nation_ref_evt(
            "NATION_002", 87, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が領域・東全域を覆うエネルギー循環網を完成した。",
            "魔導大国は展開したエネルギー循環網で領域・東の全域を覆い、魔導工学を地表生産インフラに全面適用。技術的秩序再編が限界に達した。",
            "「結晶の脈が東方を走る——すべての工房が、一つの循環に繋がった。」",
            "エネルギー循環網の完成。",
            "「物流と魔力が、同じ網の上を流れる。」",
            "東方全域を覆う光る循環網。",
            "「経済統合の器が、完成した。」",
            "循環網完成ボーナス。",
            month=5, day=20, hour=12,
            hist_suffix="ENERGY_GRID_COMPLETE",
            zone="ZONE_EAST_FORGE_BELT", mmo_flag="MMO_ZONE_EAST_FORGE_STEP_08", level=29,
        ),
    ],
    88: [
        world_evt(
            88, "MagicPioneering", "domestic",
            "【全世界】で共同再興圏への参加が千年紀末の主要潮流となった。",
            "ターン88（880年目）前後、魔導大国が提示する共同再興圏への参加が世界各地の生存国家にとって主要潮流となった。技術・物流インフラを中心とした包括的経済圏が形作られ、発展的統合が最終段階へ入った。",
            "「再興圏の契約に署名せよ——技術と結晶流通が、国を繋ぐ。」",
            "共同再興圏への参加潮流。",
            "「強国が強国を、経済で束ねる。」",
            "各地から東方へ伸びる魔導製品の交易路。",
            "「双極秩序の経済翼が、形になる。」",
            "再興圏潮流ボーナス。",
            month=10, day=5, hour=15,
            hist_suffix="JOINT_REVIVAL_WAVE",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_FINALE_STEP_04", level=29,
        ),
        nation_ref_evt(
            "NATION_015", 88, "ShieldFortification", "domestic",
            "【西方大陸南部】が千年紀の結末も形式的独立と軍事伝統を死守した。",
            "広域統治体制下へ組み込まれた南方対抗軸は、形式的な独立と独自の軍事伝統を死守し続け、西方第二極として千年紀末を迎えた。",
            "「千年紀の統合圏軍事史に、南方極のゲリラ伝統が独立章として載っている。」",
            "形式的主権と軍事伝統の維持。",
            "「統合王国の色の中に、南方だけ異なる軍旗が残る。」",
            "千年紀の南方に立つ独自の軍旗。",
            "「最大の抵抗極として、千年を完走した。」",
            "千年抵抗ボーナス。",
            related="NATION_001",
            month=12, day=20, hour=16,
            hist_suffix="POLE_TRADITION",
            zone="ZONE_WEST_SOUTH_CRYSTAL", mmo_flag="MMO_ZONE_WEST_POLE_STEP_06", level=29,
        ),
    ],
    89: [
        world_evt(
            89, "MagicPioneering", "domestic",
            "【全世界】で生存国家数が六十八カ国へ最終集約された。",
            "ターン89（890年目）前後、度重なる領域再編と発展的統合を経て、生存国家数は最終的に六十八カ国へ集約・洗練された。脆弱国の淘汰は終わり、最強の国家群だけが残った。",
            "「国は六十八——だが、どれも千年の洗練を受けた強国だ。」",
            "六十八カ国への最終集約。",
            "「地図の色は減ったが、濃さは増した。」",
            "六十八の強国に塗られた世界地図。",
            "「最終世紀の舞台が、整った。」",
            "最終集約ボーナス。",
            month=8, day=18, hour=9,
            hist_suffix="SIXTY_EIGHT_NATIONS",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_05", level=29,
        ),
    ],
    90: [
        nation_ref_evt(
            "NATION_002", 90, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が共同再興圏を形成し、双極秩序の片翼を担った。",
            "周辺国を経済的に巻き込んだ共同再興圏を形成。世界最大の魔導生産大国として、領域・西の軍事的一極秩序に対抗する経済・技術極として双極秩序の片翼を担った。",
            "「我らの魔導製品を流通網に乗せろ。周辺国は再興圏の一員として結晶契約に署名する。」",
            "共同再興圏の形成。",
            "「東方の魔導生産が、大陸を支えている。」",
            "交易路に連なる魔導製品の輸送船と結晶灯。",
            "「千年紀の双極秩序が、ここで確定する。」",
            "再興圏形成ボーナス。",
            month=10, day=1, hour=15,
            hist_suffix="DUAL_POLE_ECONOMY",
            zone="ZONE_EAST_FORGE_BELT", mmo_flag="MMO_ZONE_EAST_FORGE_STEP_09", level=30,
        ),
        world_evt(
            90, "MagicPioneering", "domestic",
            "【全世界】で双極的超大国秩序の骨格が第5章前半の頂点に達した。",
            "ターン90（900年目）時点で、領域・西の軍事統合王国と領域・東の魔導生産大国という二大巨頭による双極秩序の骨格が完成。外因的脅威の沈黙と総国力の急伸が、大国間の新たな戦略的膠着の時代を予告した。",
            "「西方に剣、東方に炉——二極が、世界を挟む。」",
            "双極秩序の骨格完成。",
            "「脅威なき地表で、人類は自分たちと向き合う。」",
            "西方と東方に立つ二種類の極。",
            "「最終世紀の後半戦が、始まる。」",
            "双極秩序ボーナス。",
            month=12, day=15, hour=18,
            hist_suffix="BIPOLAR_ORDER_FRAME",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_06", level=30,
        ),
    ],
    91: [
        world_evt(
            91, "MonsterRepelled", "monster",
            "【最西端大陸】で大遠征の殲滅戦が最終段階へ突入した。",
            "ターン91（910年目）前後、統合王国の大遠征は最西端大陸全域の掃討最終段階へ突入。空間網羅型エネルギー障壁が残存する脅威巣窟を次々と包囲し、力学的圧砕戦が加速した。",
            "「西端の浄化作戦が、最終段階に入った——巣窟は、次々と封じられる。」",
            "大遠征最終段階。",
            "「脅威の色が、地図の端から消えていく。」",
            "緑化し始める最西端大陸の地図。",
            "「完全駆逐は、目前だ。」",
            "最終段階ボーナス。",
            month=5, day=12, hour=14,
            hist_suffix="EXPEDITION_FINAL_PHASE",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_04", level=30,
        ),
    ],
    92: [
        nation_ref_evt(
            "NATION_001", 92, "MonsterRepelled", "monster",
            "【最西端の統合王国】が最西端大陸から脅威個体群の完全放逐に成功した。",
            "大遠征の総力戦の成果として、統合王国は最西端大陸全域から脅威個体群を完全に放逐することに成功。千年の戦史において、人類が特定の広大な領域から外因的脅威を完全駆逐した最初の絶対的戦果となった。",
            "「大陸西端の浄化作戦が最終段階に入った。殻虫の巣窟は次々と結晶焼却弾で封じられている。」",
            "完全放逐の達成。",
            "「最後の脅威個体群が海へ追いやられた。大陸の防衛網は完全に閉じた。」",
            "最西端大陸の地図が緑化。脅威ゾーン表示が消える。",
            "「完全放逐が達成された。統合王国は超大国として凱歌を上げる。」",
            "完全駆逐ボーナス。",
            month=12, day=31, hour=18,
            hist_suffix="THREAT_EXPULSION",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_05", level=31,
            prereq_type="MonsterEradicatedCount", prereq_val=20,
        ),
    ],
    93: [
        world_evt(
            93, "MagicPioneering", "domestic",
            "【最西端大陸】が人類の完全なる統治空間へ回帰した。",
            "ターン93（930年目）前後、脅威個体群の完全放逐を受け、最西端大陸は人類の完全なる統治空間へと回帰。能動的殲滅戦による大陸完全制圧は、後の世界秩序における軍事覇権の最高峰として歴史に楔を打ち込んだ。",
            "「この大陸に、脅威の色はもうない——人類の土地だ。」",
            "完全統治空間への回帰。",
            "「防衛線は、攻勢の成果として永久に前進した。」",
            "緑化した最西端大陸と消えた脅威ゾーン。",
            "「一極軍事秩序の頂点が、確定した。」",
            "統治空間回帰ボーナス。",
            month=3, day=8, hour=10,
            hist_suffix="ABSOLUTE_GOVERNANCE_SPACE",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_WORLD_FINALE_STEP_07", level=31,
        ),
    ],
    94: [
        nation_ref_evt(
            "NATION_002", 94, "MagicPioneering", "domestic",
            "【東方の魔導生産大国】が共同再興圏の経済統合を最終段階まで完成した。",
            "大遠征が西で進む間、魔導大国は共同再興圏の経済統合を最終段階まで推進。武力ではなく技術・経済インフラの提供によって広域秩序を構築し、世界最大の経済・技術極としての地位を不動のものとした。",
            "「再興圏の結節都市が全域で稼働している。東方の魔導生産が、大陸の経脈だ。」",
            "経済統合の最終完成。",
            "「結晶契約に署名した国々が、一つの循環網で呼吸している。」",
            "東方から中央へ伸びる魔導物流網。",
            "「双極秩序の経済翼が、完全に展開した。」",
            "経済統合完成ボーナス。",
            month=7, day=22, hour=13,
            hist_suffix="ECONOMIC_UNION_COMPLETE",
            zone="ZONE_EAST_FORGE_BELT", mmo_flag="MMO_ZONE_EAST_FORGE_STEP_10", level=31,
        ),
    ],
    95: [
        world_evt(
            95, "MonsterRepelled", "monster",
            "【最西端大陸】で大遠征が終幕を迎え、殲滅戦の号令が下ろされた。",
            "ターン95（950年目）をもって、ターン85から続いた統合王国の大遠征は終幕。領域・西全域の掃討は完了し、組織的かつ圧倒的な軍事介入によって弱体化した脅威個体群は文字通り消滅した。",
            "「全軍、凱旋せよ——大遠征は、完遂した。」",
            "大遠征の終幕。",
            "「十年の殲滅戦が、西の大陸を人間のものにした。」",
            "凱旋する遠征軍と緑化した大陸。",
            "「防衛から攻勢へ——千年の転換点。」",
            "大遠征完遂ボーナス。",
            month=11, day=11, hour=16,
            hist_suffix="GREAT_EXPEDITION_FINALE",
            zone="ZONE_WEST_CONTINENT_RIM", mmo_flag="MMO_ZONE_WEST_RIM_STEP_06", level=31,
        ),
    ],
    96: [
        world_evt(
            96, "MagicPioneering", "domestic",
            "【全世界】で総国力が未曽有の極大値へ向けて急伸した。",
            "ターン96（960年目）前後、人類全体の総国力は初期全盛期を遥かに凌駕する水準へ急伸。固有エネルギー技術の集約と広域物流網の完全復興が、千年のサバイバルの構造的果実として結実し続けた。",
            "「国力の数字が、初期の十倍を超えようとしている——千年の結晶だ。」",
            "総国力の極大化。",
            "「余剰生産力が、地表全体に溢れている。」",
            "世界中を結ぶ物流網と輝く結晶都市。",
            "「魔法技術文明の最盛期が、目前に迫る。」",
            "極大化ボーナス。",
            month=4, day=30, hour=12,
            hist_suffix="POWER_MAXIMIZATION",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_FINALE_STEP_08", level=31,
        ),
    ],
    97: [
        world_evt(
            97, "LocalConflict", "conflict",
            "【全世界】で双極超大国間の戦略的膠着が新時代の基調となった。",
            "ターン97（970年目）前後、外因的脅威の沈黙と総国力の急伸を背景に、領域・西の軍事統合王国と領域・東の魔導生産大国の間に新たな外交・戦略的膠着が生まれた。種の存亡を賭けた闘争は終わり、大国間の均衡の時代が始まった。",
            "「脅威がいなくなった今、向き合うのは自分たちだ——西に剣、東に炉。」",
            "双極間の戦略的膠着。",
            "「覇権のための統合は、完了した。次は均衡の時代。」",
            "西方と東方の極が向かい合う地政学の地図。",
            "「千年紀末の静かな対峙。」",
            "戦略膠着ボーナス。",
            month=9, day=7, hour=15,
            hist_suffix="STRATEGIC_STALEMATE",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_09", level=32,
        ),
    ],
    98: [
        world_evt(
            98, "MagicPioneering", "domestic",
            "【全世界】で千年の生存闘争が教科書的総括の対象となった。",
            "ターン98（980年目）前後、千年に及ぶ戦史は「外因的絶滅の危機が人類の国家システムを究極まで洗練させたプロセス」として後世に記録され始めた。初期崩壊から絶対防衛、大開拓、完全駆逐までの五章が、一つの大河ドラマとして結びついた。",
            "「131から68へ——淘汰と統合の千年が、一冊の叙事になる。」",
            "千年史の総括開始。",
            "「脅威は人類を強くした、という皮肉な真理。」",
            "五章の叙事が並ぶ歴史書のページ。",
            "「最終ターンが、近づいている。」",
            "千年総括ボーナス。",
            month=6, day=18, hour=11,
            hist_suffix="MILLENNIUM_RETROSPECT",
            zone="ZONE_WORLD_TRADE_ROUTE", mmo_flag="MMO_WORLD_FINALE_STEP_10", level=32,
        ),
    ],
    99: [
        world_evt(
            99, "MagicPioneering", "domestic",
            "【全世界】で最終確定データに向けた観測が始まった。",
            "ターン99（990年目）前後、世界全体の平均脅威度は0.5の最低水準を維持し、生存国家数六十八、総国力の極大値への到達が目前となった。各地の強国は千年紀の結末を静かに迎えようとしている。",
            "「あと一ターン——千年の記録が、最終ページへ。」",
            "最終確定へのカウントダウン。",
            "「六十八の強国が、静かに結末を待つ。」",
            "世界地図に刻まれた六十八の色。",
            "「次のターンで、叙事は止まる。」",
            "最終カウントダウンボーナス。",
            month=12, day=1, hour=0,
            hist_suffix="FINAL_COUNTDOWN",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_11", level=32,
        ),
    ],
    100: [
        world_evt(
            100, "MagicPioneering", "domestic",
            "【全世界】で千年の歴史シミュレーションが停止した。",
            "ターン100（1000年目）の最終確定。生存国数六十八、人類総国力は二十二万超、平均脅威度0.5——この数値をもって千年の歴史シミュレーションは停止した。人類は最西端大陸から脅威を完全放逐し、双極的超大国秩序の下で次なる文明の地平へ向かう足がかりを得た。",
            "「千年——131から68へ、一万九千から二十二万へ。叙事は、ここで止まる。」",
            "千年シミュレーション停止。",
            "「種は生き残った。文明は、十倍以上に強くなった。」",
            "静かに閉じる歴史書と、新しい地平線。",
            "「第5章完——千年の戦史に、幕。」",
            "千年完結ボーナス。",
            month=12, day=31, hour=23,
            hist_suffix="MILLENNIUM_SIMULATION_STOP",
            zone="ZONE_WORLD_FRONTIER", mmo_flag="MMO_WORLD_FINALE_STEP_12", level=33,
        ),
        nation_ref_evt(
            "NATION_001", 100, "MagicPioneering", "domestic",
            "【最西端の統合王国】が世界最強の軍事超大国として千年紀の結末を迎えた。",
            "完全駆逐と大遠征の成果を受け、統合王国は世界最強の軍事的一極秩序として千年紀の結末を迎えた。能動的殲滅戦による大陸完全制圧は、人類史における覇権的達成の最高峰として記録された。",
            "「統合王国は千年紀の結末を、超大国として迎える。」",
            "軍事超大国としての千年紀完走。",
            "「西方の太陽は、千年燃え続けた。」",
            "最西端大陸を照らす統合の光。",
            "「次なる千年紀への、最強の足がかり。」",
            "超大国完結ボーナス。",
            month=12, day=31, hour=18,
            hist_suffix="MILITARY_SUPERPOWER_FINALE",
            zone="ZONE_WEST_INTEGRATION_BELT", mmo_flag="MMO_ZONE_WEST_INTEGRATION_STEP_21", level=33,
        ),
    ],
}
